
server {

    listen 80;



    location / {

        root /usr/share/nginx/html;

        try_files $uri $uri/ /index.html;

    }



    location /api/auth/ {

        proxy_pass http://auth_service:8001/;

        proxy_set_header Host $host;

    }

    location /api/dashboard/ {

        proxy_pass http://dashboard_service:8002/;

        proxy_set_header Host $host;

    }

    location /api/search/ {

        proxy_pass http://search_service:8003/;

        proxy_set_header Host $host;

    }

    location /api/notifications/ {

        proxy_pass http://notifications_service:8004/;

        proxy_set_header Host $host;

    }

}

