# Este docker compose es para poder hacer cambios y que se 
# vean reflejados en tiempo real y que no haga falta cerrar 
# el docker compose y volver a levantarlo para poder ver los cambios efectuados

# Para poder correrlo en la terminal debes ejecutar el siguiente comando en la Git Bash:

# docker compose -f docker-compose.dev.yml up --build

services:

  search_service:
    build: ./services/search_service
    container_name: search_service
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: mysql+pymysql://coniiti:coniiti@181.79.5.78:3306/db_search
      NOTIFICATIONS_SERVICE_URL: http://notifications_service:8004
    volumes:
      - ./services/search_service:/app
      - speaker_images:/app/uploads/speakers
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
    networks:
      - coniiti_network
    restart: unless-stopped

  dashboard_service:
    build: ./services/dashboard_service
    container_name: dashboard_service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: mysql+pymysql://coniiti:coniiti@181.79.5.78:3306/db_dashboard
      SEARCH_SERVICE_URL: http://search_service:8003
    volumes:
      - ./services/dashboard_service:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    depends_on:
      - search_service
    networks:
      - coniiti_network
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      SEARCH_SERVICE_URL: http://search_service:8003
    volumes:
      - ./Frontend/src:/app/src
      - ./Frontend/public:/app/public
      - ./Frontend/index.html:/app/index.html
    depends_on:
      - search_service
      - dashboard_service
    networks:
      - coniiti_network
    restart: unless-stopped

volumes:
  speaker_images:

networks:
  coniiti_network:
    driver: bridge
