import { createContext, useContext, useState, ReactNode } from "react";

export type LangCode = "ES" | "EN" | "IT" | "PT" | "FR";

export const LANGUAGES: { code: LangCode; flag: string; name: string }[] = [
  { code: "ES", flag: "🇪🇸", name: "Español"   },
  { code: "EN", flag: "🇺🇸", name: "English"   },
  { code: "IT", flag: "🇮🇹", name: "Italiano"  },
  { code: "PT", flag: "🇧🇷", name: "Português" },
  { code: "FR", flag: "🇫🇷", name: "Français"  },
];

type T = Record<string, string>;

const ES: T = {
  /* Navbar */
  home: "Home", nosotros: "Nosotros", ferias: "Nuestras ferias",
  inscripciones: "Inscripciones", noticias: "Noticias", ponentes: "Ponentes", login: "Ingresar",
  register: "Crear cuenta",
  buscar: "Buscar...",
  /* Hero */
  hero_title: "Coniiti 2026", hero_country: "País invitado: Italia",
  hero_speakers: "Conferencistas internacionales",
  /* Stats */
  stat_speakers: "Conferencistas", stat_sponsors: "Patrocinadores",
  stat_workshops: "Talleres", stat_attendees: "Participantes",
  stat_host: "País anfitrión", stat_days: "Días de evento",
  /* Countdown */
  days: "Días", hours: "Horas", minutes: "Minutos", seconds: "Segundos",
  /* Tarjetas Home */
  card1_title: "Home", card1_p: "Explora nuestra información principal.",
  card2_title: "Nuestras Ferias", card2_p: "Eventos académicos y empresariales.",
  card3_title: "Inscripciones", card3_p: "Conoce los pasos para aplicar.",
  card4_title: "Noticias", card4_p: "Mantente informado.",
  /* Nosotros */
  nos_what: "¿Qué es CONIITI?",
  nos_what_p: "El Congreso Internacional de Innovación y Tendencias en Ingeniería es el evento académico insignia de la Universidad Católica de Colombia. En su XII edición, CONIITI 2026 tiene como país invitado a Italia.",
  nos_history: "Historia",
  nos_history_p: "Desde 2014, CONIITI ha crecido de un evento nacional a un congreso con presencia en más de 20 países. Cada edición ha impulsado la publicación de investigaciones indexadas y el fortalecimiento de redes internacionales.",
  nos_uni: "Universidad Organizadora",
  nos_uni_p: "La Universidad Católica de Colombia, con más de 50 años de historia y acreditación de alta calidad, es la sede y alma de CONIITI. Su Facultad de Ingeniería lidera cada edición con rigor académico y visión global.",
  nos_visit: "Visitar sitio oficial →",
  nos_goals: "Objetivos",
  goal1_t: "Internacionalización", goal1_p: "Intercambio de conocimiento entre ingenieros del mundo.",
  goal2_t: "Innovación", goal2_p: "Últimas tendencias tecnológicas e investigaciones aplicadas.",
  goal3_t: "Networking", goal3_p: "Redes entre académicos, empresas e investigadores.",
  goal4_t: "Formación", goal4_p: "Fortalecimiento de competencias en ingeniería.",
  /* Footer */
  footer_center: "Centro de Convenciones",
  footer_rights: "© 2026 CONIITI - Todos los derechos reservados",
  /* Login */
  back: "Volver al inicio",
  /* Dashboard nav */
  dash_profile: "Perfil", dash_conferences: "Mis conferencias", dash_completed: "Completadas",
  dash_events: "Eventos", dash_favorites: "Favoritos", dash_calendar: "Calendario",
  dash_messages: "Mensajes", dash_settings: "Ajustes", dash_logout: "Cerrar sesión",
  dash_mobile_talks: "Mis charlas", dash_go_home: "Inicio", dash_loading: "Cargando…",
  dash_welcome_back: "Bienvenido de nuevo,", dash_welcome_first: "¡Bienvenido al CONIITI 2026!",
  dash_notifications: "Notificaciones",
  /* ProfileView */
  prof_reg_date: "Fecha de registro:", prof_country: "País, ciudad:",
  prof_birthdate: "Fecha de nacimiento:", prof_email: "E-mail:", prof_phone: "Teléfono:",
  prof_upcoming: "Próximo evento", prof_event_subtitle: "20 octubre · Bogotá, Colombia",
  prof_days: "días", prof_hours: "horas", prof_min: "min", prof_seg: "seg",
  prof_day0: "Lun 20 Oct", prof_day1: "Mar 21 Oct", prof_day2: "Mié 22 Oct", prof_day3: "Jue 23 Oct",
  prof_no_tickets: "Sin entradas",
  prof_no_tickets_sub: "Aún no estás inscrito en ninguna conferencia del CONIITI 2026.",
  prof_explore: "Explorar conferencias", prof_prev: "Anterior", prof_next_ticket: "Siguiente",
  prof_edit: "Editar perfil", prof_loading: "Cargando…",
  /* InscritasView */
  iv_kpi_total: "Total inscritas", iv_kpi_confirmed: "Confirmadas",
  iv_kpi_ongoing: "En curso", iv_kpi_finished: "Finalizadas",
  iv_search_ph: "Buscar por conferencia, ponente, salón o categoría...",
  iv_show_all: "Mostrar Todas", iv_conference_s: "conferencia", iv_conference_pl: "conferencias",
  iv_back_cats: "Volver a Categorías", iv_no_results: "No se encontraron conferencias",
  iv_matching: "que coincidan con",
  iv_th_conference: "Conferencia", iv_th_category: "Categoría", iv_th_status: "Estado",
  iv_th_speaker: "Ponente", iv_th_location: "Ubicación", iv_th_schedule: "Horario",
  iv_status_confirmed: "Confirmada", iv_status_ongoing: "En curso", iv_status_finished: "Finalizada",
  iv_cancel_action: "Cancelar inscripción", iv_loading: "Cargando tus conferencias…",
  iv_empty_title: "Aún no tienes conferencias inscritas en la CONIITI 2026",
  iv_empty_sub: "¡Explora el cronograma e inscríbete a tus favoritas!",
  iv_explore: "Explorar conferencias", iv_no_results_cat: "No hay conferencias en esta categoría",
  iv_no_results_q: "Sin resultados para", iv_cancel_ok: "Inscripción a \"{0}\" cancelada",
  iv_cancel_fail: "No se pudo cancelar la inscripción", iv_conn_error: "Error de conexión",
  iv_load_error: "No se pudieron cargar las conferencias",
  /* SettingsView */
  stv_tab_profile: "Datos de perfil", stv_tab_security: "Seguridad", stv_tab_prefs: "Preferencias",
  stv_field_name: "Nombre completo", stv_field_phone: "Teléfono",
  stv_field_city: "Ciudad / País", stv_field_birthdate: "Fecha de nacimiento",
  stv_save: "Guardar cambios", stv_saving: "Guardando…",
  stv_saved_ok: "Perfil actualizado correctamente.",
  stv_save_error: "No se pudo guardar. Verifica tu conexión.",
  stv_field_cur_pwd: "Contraseña actual", stv_field_new_pwd: "Nueva contraseña",
  stv_field_confirm_pwd: "Confirmar nueva contraseña",
  stv_pwd_min_hint: "Mínimo 6 caracteres", stv_pwd_repeat_hint: "Repite la contraseña",
  stv_update_pwd: "Actualizar contraseña", stv_updating: "Actualizando…",
  stv_pwd_ok: "Contraseña actualizada correctamente.",
  stv_pwd_short: "La nueva contraseña debe tener al menos 6 caracteres.",
  stv_pwd_mismatch: "Las contraseñas nuevas no coinciden.",
  stv_pwd_error: "No se pudo actualizar la contraseña.",
  stv_theme_title: "Tema de la interfaz",
  stv_theme_light: "Claro UCC", stv_theme_light_desc: "Azul y blanco institucional",
  stv_theme_dark: "Oscuro UCC", stv_theme_dark_desc: "Modo nocturno con acentos dorados",
  stv_theme_system: "Sistema", stv_theme_system_desc: "Sigue la preferencia del dispositivo",
  stv_compact_title: "Vista compacta",
  stv_compact_on: "Activada — menos espacio entre elementos",
  stv_compact_off: "Desactivada — espaciado estándar",
  /* MessagesView */
  msv_loading: "Cargando mensajes…", msv_error: "No se pudieron cargar los mensajes.",
  msv_empty_title: "Sin mensajes",
  msv_empty_sub: "Cuando el sistema te envíe notificaciones, aparecerán aquí.",
  msv_heading: "Mensajes", msv_unread: "{0} sin leer", msv_mark_read: "Marcar como leído",
  msv_unread_label: "No leído", msv_type_info: "Info", msv_type_alerta: "Alerta",
  msv_type_sistema: "Sistema",
  /* PlaceholderView */
  ph_favorites_title: "Favoritos", ph_favorites_msg: "Función de favoritos próximamente disponible.",
  ph_events_title: "Eventos", ph_completed_title: "Completadas",
  ph_system_ready: "El sistema está listo para recibir estos datos en la siguiente fase del proyecto.",
  ph_soon: "Próximamente", ph_dev_title: "Sección en desarrollo",
  ph_dev_msg: "Esta funcionalidad estará disponible próximamente.",
  /* Ticket */
  prof_ticket_sede: "SEDE", prof_ticket_sala: "SALA", prof_ticket_serial: "SERIAL",
  prof_ticket_venue: "Universidad Católica de Colombia",
  /* Home hardcoded */
  hero_edition: "XII Edición · Bogotá, Colombia",
  hero_tagline: "El congreso internacional que conecta la ingeniería del futuro.",
  hero_cta: "Inscríbete al congreso",
  hero_city: "Bogotá, Colombia",
  hero_date: "23 de septiembre, 2026",
  hero_guest: "País invitado",
  countdown_label: "El congreso comienza en",
  home_discover: "Descubre CONIITI 2026",
  home_discover_sub: "Explora cada rincón del congreso internacional de ingeniería",
  /* Inscripciones */
  insc_title: "Conferencias CONIITI 2026",
  insc_sub: "Explora el catálogo de charlas y regístrate en las que más te interesen",
  insc_search_ph: "Buscar por título, ponente o tema…",
  insc_loading: "Cargando conferencias…",
  insc_retry: "Reintentar",
  insc_empty: "No se encontraron conferencias con esos filtros.",
  insc_spots_none: "Sin cupos disponibles",
  insc_spots: "cupo disponible",
  insc_spots_pl: "cupos disponibles",
  insc_register: "Inscribirme",
  insc_cancel: "Cancelar inscripción",
  insc_registering: "Inscribiendo…",
  insc_cancelling: "Cancelando…",
  insc_full: "Sin cupos",
  insc_registered_badge: "Inscrito",
  insc_to_define: "Por definir",
};

const EN: T = {
  /* Dashboard nav */
  dash_profile: "Profile", dash_conferences: "My Conferences", dash_completed: "Completed",
  dash_events: "Events", dash_favorites: "Favorites", dash_calendar: "Calendar",
  dash_messages: "Messages", dash_settings: "Settings", dash_logout: "Log out",
  dash_mobile_talks: "My talks", dash_go_home: "Home", dash_loading: "Loading…",
  dash_welcome_back: "Welcome back,", dash_welcome_first: "Welcome to CONIITI 2026!",
  dash_notifications: "Notifications",
  /* ProfileView */
  prof_reg_date: "Registration date:", prof_country: "Country, city:",
  prof_birthdate: "Date of birth:", prof_email: "E-mail:", prof_phone: "Phone:",
  prof_upcoming: "Upcoming event", prof_event_subtitle: "October 20 · Bogotá, Colombia",
  prof_days: "days", prof_hours: "hours", prof_min: "min", prof_seg: "sec",
  prof_day0: "Mon Oct 20", prof_day1: "Tue Oct 21", prof_day2: "Wed Oct 22", prof_day3: "Thu Oct 23",
  prof_no_tickets: "No tickets",
  prof_no_tickets_sub: "You are not yet registered for any conference at CONIITI 2026.",
  prof_explore: "Explore conferences", prof_prev: "Previous", prof_next_ticket: "Next",
  prof_edit: "Edit profile", prof_loading: "Loading…",
  /* InscritasView */
  iv_kpi_total: "Total registered", iv_kpi_confirmed: "Confirmed",
  iv_kpi_ongoing: "Ongoing", iv_kpi_finished: "Finished",
  iv_search_ph: "Search by conference, speaker, room or category...",
  iv_show_all: "Show All", iv_conference_s: "conference", iv_conference_pl: "conferences",
  iv_back_cats: "Back to Categories", iv_no_results: "No conferences found",
  iv_matching: "matching",
  iv_th_conference: "Conference", iv_th_category: "Category", iv_th_status: "Status",
  iv_th_speaker: "Speaker", iv_th_location: "Location", iv_th_schedule: "Schedule",
  iv_status_confirmed: "Confirmed", iv_status_ongoing: "Ongoing", iv_status_finished: "Finished",
  iv_cancel_action: "Cancel registration", iv_loading: "Loading your conferences…",
  iv_empty_title: "You have no conferences registered at CONIITI 2026 yet",
  iv_empty_sub: "Explore the schedule and register for your favorites!",
  iv_explore: "Explore conferences", iv_no_results_cat: "No conferences in this category",
  iv_no_results_q: "No results for", iv_cancel_ok: "Registration for \"{0}\" cancelled",
  iv_cancel_fail: "Could not cancel the registration", iv_conn_error: "Connection error",
  iv_load_error: "Could not load conferences",
  /* SettingsView */
  stv_tab_profile: "Profile data", stv_tab_security: "Security", stv_tab_prefs: "Preferences",
  stv_field_name: "Full name", stv_field_phone: "Phone",
  stv_field_city: "City / Country", stv_field_birthdate: "Date of birth",
  stv_save: "Save changes", stv_saving: "Saving…",
  stv_saved_ok: "Profile updated successfully.",
  stv_save_error: "Could not save. Check your connection.",
  stv_field_cur_pwd: "Current password", stv_field_new_pwd: "New password",
  stv_field_confirm_pwd: "Confirm new password",
  stv_pwd_min_hint: "Minimum 6 characters", stv_pwd_repeat_hint: "Repeat the password",
  stv_update_pwd: "Update password", stv_updating: "Updating…",
  stv_pwd_ok: "Password updated successfully.",
  stv_pwd_short: "The new password must be at least 6 characters.",
  stv_pwd_mismatch: "The new passwords do not match.",
  stv_pwd_error: "Could not update the password.",
  stv_theme_title: "Interface theme",
  stv_theme_light: "Light UCC", stv_theme_light_desc: "Institutional blue and white",
  stv_theme_dark: "Dark UCC", stv_theme_dark_desc: "Night mode with golden accents",
  stv_theme_system: "System", stv_theme_system_desc: "Follows device preference",
  stv_compact_title: "Compact view",
  stv_compact_on: "Enabled — less space between elements",
  stv_compact_off: "Disabled — standard spacing",
  /* MessagesView */
  msv_loading: "Loading messages…", msv_error: "Could not load messages.",
  msv_empty_title: "No messages",
  msv_empty_sub: "When the system sends you notifications, they will appear here.",
  msv_heading: "Messages", msv_unread: "{0} unread", msv_mark_read: "Mark as read",
  msv_unread_label: "Unread", msv_type_info: "Info", msv_type_alerta: "Alert",
  msv_type_sistema: "System",
  /* PlaceholderView */
  ph_favorites_title: "Favorites", ph_favorites_msg: "Favorites feature coming soon.",
  ph_events_title: "Events", ph_completed_title: "Completed",
  ph_system_ready: "The system is ready to receive this data in the next project phase.",
  ph_soon: "Coming soon", ph_dev_title: "Section under development",
  ph_dev_msg: "This functionality will be available soon.",

  home: "Home", nosotros: "About Us", ferias: "Our Fairs",
  inscripciones: "Registrations", noticias: "News", ponentes: "Speakers", login: "Login",
  register: "Sign Up",
  buscar: "Search...",
  hero_title: "Coniiti 2026", hero_country: "Guest Country: Italy",
  hero_speakers: "International Speakers",
  stat_speakers: "Speakers", stat_sponsors: "Sponsors",
  stat_workshops: "Workshops", stat_attendees: "Attendees",
  stat_host: "Host Country", stat_days: "Event Days",
  days: "Days", hours: "Hours", minutes: "Minutes", seconds: "Seconds",
  card1_title: "Home", card1_p: "Explore our main information.",
  card2_title: "Our Fairs", card2_p: "Academic and business events.",
  card3_title: "Registrations", card3_p: "Learn the steps to apply.",
  card4_title: "News", card4_p: "Stay informed.",
  nos_what: "What is CONIITI?",
  nos_what_p: "The International Congress of Innovation and Trends in Engineering is the flagship academic event of Universidad Católica de Colombia. In its XII edition, CONIITI 2026 welcomes Italy as guest country.",
  nos_history: "History",
  nos_history_p: "Since 2014, CONIITI has grown from a national event to a congress with presence in more than 20 countries. Each edition has driven the publication of indexed research and the strengthening of international networks.",
  nos_uni: "Organizing University",
  nos_uni_p: "Universidad Católica de Colombia, with more than 50 years of history and high quality accreditation, is the home of CONIITI. Its Faculty of Engineering leads each edition with academic rigor and global vision.",
  nos_visit: "Visit official site →",
  nos_goals: "Goals",
  goal1_t: "Internationalization", goal1_p: "Knowledge exchange among engineers worldwide.",
  goal2_t: "Innovation", goal2_p: "Latest technological trends and applied research.",
  goal3_t: "Networking", goal3_p: "Networks among academics, companies and researchers.",
  goal4_t: "Training", goal4_p: "Strengthening engineering competencies.",
  footer_center: "Convention Center",
  footer_rights: "© 2026 CONIITI - All rights reserved",
  back: "Back to home",
  hero_edition: "XII Edition · Bogotá, Colombia",
  hero_tagline: "The international congress connecting the engineering of the future.",
  hero_cta: "Register for the congress",
  hero_city: "Bogotá, Colombia",
  hero_date: "September 23, 2026",
  hero_guest: "Guest country",
  countdown_label: "The congress begins in",
  home_discover: "Discover CONIITI 2026",
  home_discover_sub: "Explore every corner of the international engineering congress",
  insc_title: "CONIITI 2026 Conferences",
  insc_sub: "Browse the talk catalogue and register for the ones you find most interesting",
  insc_search_ph: "Search by title, speaker or topic…",
  insc_loading: "Loading conferences…",
  insc_retry: "Retry",
  insc_empty: "No conferences found with those filters.",
  insc_spots_none: "No spots available",
  insc_spots: "spot available",
  insc_spots_pl: "spots available",
  insc_register: "Register",
  insc_cancel: "Cancel registration",
  insc_registering: "Registering…",
  insc_cancelling: "Cancelling…",
  insc_full: "Full",
  insc_registered_badge: "Registered",
  insc_to_define: "To be defined",
  /* Ticket */
  prof_ticket_sede: "VENUE", prof_ticket_sala: "ROOM", prof_ticket_serial: "SERIAL",
  prof_ticket_venue: "Universidad Católica de Colombia",
};

const IT: T = {
  home: "Home", nosotros: "Chi Siamo", ferias: "Le Nostre Fiere",
  inscripciones: "Iscrizioni", noticias: "Notizie", ponentes: "Relatori", login: "Accedi",
  register: "Registrati",
  buscar: "Cerca...",
  hero_title: "Coniiti 2026", hero_country: "Paese ospite: Italia",
  hero_speakers: "Relatori internazionali",
  stat_speakers: "Relatori", stat_sponsors: "Sponsor",
  stat_workshops: "Workshop", stat_attendees: "Partecipanti",
  stat_host: "Paese ospitante", stat_days: "Giorni di evento",
  days: "Giorni", hours: "Ore", minutes: "Minuti", seconds: "Secondi",
  card1_title: "Home", card1_p: "Esplora le nostre informazioni principali.",
  card2_title: "Le Nostre Fiere", card2_p: "Eventi accademici e aziendali.",
  card3_title: "Iscrizioni", card3_p: "Scopri i passi per candidarsi.",
  card4_title: "Notizie", card4_p: "Rimani informato.",
  nos_what: "Cos'è CONIITI?",
  nos_what_p: "Il Congresso Internazionale di Innovazione e Tendenze nell'Ingegneria è l'evento accademico di punta dell'Università Cattolica della Colombia. Nella sua XII edizione, CONIITI 2026 ha l'Italia come paese ospite.",
  nos_history: "Storia",
  nos_history_p: "Dal 2014, CONIITI è cresciuto da un evento nazionale a un congresso con presenza in più di 20 paesi. Ogni edizione ha promosso la pubblicazione di ricerche indicizzate.",
  nos_uni: "Università Organizzatrice",
  nos_uni_p: "L'Università Cattolica della Colombia, con oltre 50 anni di storia e accreditamento di alta qualità, è la sede di CONIITI.",
  nos_visit: "Visita il sito ufficiale →",
  nos_goals: "Obiettivi",
  goal1_t: "Internazionalizzazione", goal1_p: "Scambio di conoscenze tra ingegneri del mondo.",
  goal2_t: "Innovazione", goal2_p: "Ultime tendenze tecnologiche e ricerche applicate.",
  goal3_t: "Networking", goal3_p: "Reti tra accademici, aziende e ricercatori.",
  goal4_t: "Formazione", goal4_p: "Rafforzamento delle competenze ingegneristiche.",
  footer_center: "Centro Congressi",
  footer_rights: "© 2026 CONIITI - Tutti i diritti riservati",
  back: "Torna alla home",
  hero_edition: "XII Edizione · Bogotá, Colombia",
  hero_tagline: "Il congresso internazionale che connette l'ingegneria del futuro.",
  hero_cta: "Iscriviti al congresso",
  hero_city: "Bogotá, Colombia",
  hero_date: "23 settembre 2026",
  hero_guest: "Paese ospite",
  countdown_label: "Il congresso inizia tra",
  home_discover: "Scopri CONIITI 2026",
  home_discover_sub: "Esplora ogni angolo del congresso internazionale di ingegneria",
  insc_title: "Conferenze CONIITI 2026",
  insc_sub: "Esplora il catalogo di conferenze e iscriviti a quelle che ti interessano",
  insc_search_ph: "Cerca per titolo, relatore o tema…",
  insc_loading: "Caricamento conferenze…",
  insc_retry: "Riprova",
  insc_empty: "Nessuna conferenza trovata con questi filtri.",
  insc_spots_none: "Nessun posto disponibile",
  insc_spots: "posto disponibile",
  insc_spots_pl: "posti disponibili",
  insc_register: "Iscrivimi",
  insc_cancel: "Annulla iscrizione",
  insc_registering: "Iscrizione in corso…",
  insc_cancelling: "Annullamento…",
  insc_full: "Completo",
  insc_registered_badge: "Iscritto",
  insc_to_define: "Da definire",
  /* Dashboard nav */
  dash_profile: "Profilo", dash_conferences: "Le mie conferenze", dash_completed: "Completate",
  dash_events: "Eventi", dash_favorites: "Preferiti", dash_calendar: "Calendario",
  dash_messages: "Messaggi", dash_settings: "Impostazioni", dash_logout: "Esci",
  dash_mobile_talks: "I miei talk", dash_go_home: "Inizio", dash_loading: "Caricamento…",
  dash_welcome_back: "Bentornato,", dash_welcome_first: "Benvenuto al CONIITI 2026!",
  dash_notifications: "Notifiche",
  /* ProfileView */
  prof_reg_date: "Data di registrazione:", prof_country: "Paese, città:",
  prof_birthdate: "Data di nascita:", prof_email: "E-mail:", prof_phone: "Telefono:",
  prof_upcoming: "Prossimo evento", prof_event_subtitle: "20 ottobre · Bogotá, Colombia",
  prof_days: "giorni", prof_hours: "ore", prof_min: "min", prof_seg: "sec",
  prof_day0: "Lun 20 Ott", prof_day1: "Mar 21 Ott", prof_day2: "Mer 22 Ott", prof_day3: "Gio 23 Ott",
  prof_no_tickets: "Nessun biglietto",
  prof_no_tickets_sub: "Non sei ancora iscritto a nessuna conferenza del CONIITI 2026.",
  prof_explore: "Esplora le conferenze", prof_prev: "Precedente", prof_next_ticket: "Successivo",
  prof_edit: "Modifica profilo", prof_loading: "Caricamento…",
  /* InscritasView */
  iv_kpi_total: "Totale iscritte", iv_kpi_confirmed: "Confermate",
  iv_kpi_ongoing: "In corso", iv_kpi_finished: "Terminate",
  iv_search_ph: "Cerca per conferenza, relatore, sala o categoria...",
  iv_show_all: "Mostra Tutte", iv_conference_s: "conferenza", iv_conference_pl: "conferenze",
  iv_back_cats: "Torna alle Categorie", iv_no_results: "Nessuna conferenza trovata",
  iv_matching: "corrispondente a",
  iv_th_conference: "Conferenza", iv_th_category: "Categoria", iv_th_status: "Stato",
  iv_th_speaker: "Relatore", iv_th_location: "Ubicazione", iv_th_schedule: "Orario",
  iv_status_confirmed: "Confermata", iv_status_ongoing: "In corso", iv_status_finished: "Terminata",
  iv_cancel_action: "Annulla iscrizione", iv_loading: "Caricamento delle conferenze…",
  iv_empty_title: "Non hai ancora conferenze iscritte al CONIITI 2026",
  iv_empty_sub: "Esplora il programma e iscriviti alle tue preferite!",
  iv_explore: "Esplora le conferenze", iv_no_results_cat: "Nessuna conferenza in questa categoria",
  iv_no_results_q: "Nessun risultato per", iv_cancel_ok: "Iscrizione a \"{0}\" annullata",
  iv_cancel_fail: "Impossibile annullare l'iscrizione", iv_conn_error: "Errore di connessione",
  iv_load_error: "Impossibile caricare le conferenze",
  /* SettingsView */
  stv_tab_profile: "Dati del profilo", stv_tab_security: "Sicurezza", stv_tab_prefs: "Preferenze",
  stv_field_name: "Nome completo", stv_field_phone: "Telefono",
  stv_field_city: "Città / Paese", stv_field_birthdate: "Data di nascita",
  stv_save: "Salva modifiche", stv_saving: "Salvataggio…",
  stv_saved_ok: "Profilo aggiornato con successo.",
  stv_save_error: "Impossibile salvare. Verifica la connessione.",
  stv_field_cur_pwd: "Password attuale", stv_field_new_pwd: "Nuova password",
  stv_field_confirm_pwd: "Conferma nuova password",
  stv_pwd_min_hint: "Minimo 6 caratteri", stv_pwd_repeat_hint: "Ripeti la password",
  stv_update_pwd: "Aggiorna password", stv_updating: "Aggiornamento…",
  stv_pwd_ok: "Password aggiornata con successo.",
  stv_pwd_short: "La nuova password deve avere almeno 6 caratteri.",
  stv_pwd_mismatch: "Le nuove password non coincidono.",
  stv_pwd_error: "Impossibile aggiornare la password.",
  stv_theme_title: "Tema dell'interfaccia",
  stv_theme_light: "Chiaro UCC", stv_theme_light_desc: "Blu e bianco istituzionale",
  stv_theme_dark: "Scuro UCC", stv_theme_dark_desc: "Modalità notturna con accenti dorati",
  stv_theme_system: "Sistema", stv_theme_system_desc: "Segue le preferenze del dispositivo",
  stv_compact_title: "Vista compatta",
  stv_compact_on: "Abilitata — meno spazio tra gli elementi",
  stv_compact_off: "Disabilitata — spaziatura standard",
  /* MessagesView */
  msv_loading: "Caricamento messaggi…", msv_error: "Impossibile caricare i messaggi.",
  msv_empty_title: "Nessun messaggio",
  msv_empty_sub: "Quando il sistema ti invierà notifiche, appariranno qui.",
  msv_heading: "Messaggi", msv_unread: "{0} non letti", msv_mark_read: "Segna come letto",
  msv_unread_label: "Non letto", msv_type_info: "Info", msv_type_alerta: "Allerta",
  msv_type_sistema: "Sistema",
  /* PlaceholderView */
  ph_favorites_title: "Preferiti", ph_favorites_msg: "Funzione preferiti disponibile a breve.",
  ph_events_title: "Eventi", ph_completed_title: "Completate",
  ph_system_ready: "Il sistema è pronto per ricevere questi dati nella prossima fase del progetto.",
  ph_soon: "Prossimamente", ph_dev_title: "Sezione in sviluppo",
  ph_dev_msg: "Questa funzionalità sarà disponibile a breve.",
  /* Ticket */
  prof_ticket_sede: "SEDE", prof_ticket_sala: "SALA", prof_ticket_serial: "SERIALE",
  prof_ticket_venue: "Universidad Católica de Colombia",
};

const PT: T = {
  home: "Início", nosotros: "Sobre Nós", ferias: "Nossas Feiras",
  inscripciones: "Inscrições", noticias: "Notícias", ponentes: "Palestrantes", login: "Entrar",
  register: "Cadastrar",
  buscar: "Buscar...",
  hero_title: "Coniiti 2026", hero_country: "País convidado: Itália",
  hero_speakers: "Palestrantes internacionais",
  stat_speakers: "Palestrantes", stat_sponsors: "Patrocinadores",
  stat_workshops: "Oficinas", stat_attendees: "Participantes",
  stat_host: "País anfitrião", stat_days: "Dias de evento",
  days: "Dias", hours: "Horas", minutes: "Minutos", seconds: "Segundos",
  card1_title: "Início", card1_p: "Explore nossas informações principais.",
  card2_title: "Nossas Feiras", card2_p: "Eventos acadêmicos e empresariais.",
  card3_title: "Inscrições", card3_p: "Conheça os passos para se inscrever.",
  card4_title: "Notícias", card4_p: "Fique informado.",
  nos_what: "O que é CONIITI?",
  nos_what_p: "O Congresso Internacional de Inovação e Tendências em Engenharia é o evento acadêmico principal da Universidade Católica da Colômbia. Em sua XII edição, CONIITI 2026 tem a Itália como país convidado.",
  nos_history: "História",
  nos_history_p: "Desde 2014, o CONIITI cresceu de um evento nacional para um congresso com presença em mais de 20 países.",
  nos_uni: "Universidade Organizadora",
  nos_uni_p: "A Universidade Católica da Colômbia, com mais de 50 anos de história e acreditação de alta qualidade, é a sede do CONIITI.",
  nos_visit: "Visitar site oficial →",
  nos_goals: "Objetivos",
  goal1_t: "Internacionalização", goal1_p: "Troca de conhecimento entre engenheiros do mundo.",
  goal2_t: "Inovação", goal2_p: "Últimas tendências tecnológicas e pesquisas aplicadas.",
  goal3_t: "Networking", goal3_p: "Redes entre acadêmicos, empresas e pesquisadores.",
  goal4_t: "Formação", goal4_p: "Fortalecimento de competências em engenharia.",
  footer_center: "Centro de Convenções",
  footer_rights: "© 2026 CONIITI - Todos os direitos reservados",
  back: "Voltar ao início",
  hero_edition: "XII Edição · Bogotá, Colômbia",
  hero_tagline: "O congresso internacional que conecta a engenharia do futuro.",
  hero_cta: "Inscreva-se no congresso",
  hero_city: "Bogotá, Colômbia",
  hero_date: "23 de setembro de 2026",
  hero_guest: "País convidado",
  countdown_label: "O congresso começa em",
  home_discover: "Descubra o CONIITI 2026",
  home_discover_sub: "Explore cada canto do congresso internacional de engenharia",
  insc_title: "Conferências CONIITI 2026",
  insc_sub: "Explore o catálogo de palestras e inscreva-se nas que mais lhe interessam",
  insc_search_ph: "Buscar por título, palestrante ou tema…",
  insc_loading: "Carregando conferências…",
  insc_retry: "Tentar novamente",
  insc_empty: "Nenhuma conferência encontrada com esses filtros.",
  insc_spots_none: "Sem vagas disponíveis",
  insc_spots: "vaga disponível",
  insc_spots_pl: "vagas disponíveis",
  insc_register: "Inscrever-me",
  insc_cancel: "Cancelar inscrição",
  insc_registering: "Inscrevendo…",
  insc_cancelling: "Cancelando…",
  insc_full: "Sem vagas",
  insc_registered_badge: "Inscrito",
  insc_to_define: "A definir",
  /* Dashboard nav */
  dash_profile: "Perfil", dash_conferences: "Minhas conferências", dash_completed: "Concluídas",
  dash_events: "Eventos", dash_favorites: "Favoritos", dash_calendar: "Calendário",
  dash_messages: "Mensagens", dash_settings: "Configurações", dash_logout: "Sair",
  dash_mobile_talks: "Minhas palestras", dash_go_home: "Início", dash_loading: "Carregando…",
  dash_welcome_back: "Bem-vindo de volta,", dash_welcome_first: "Bem-vindo ao CONIITI 2026!",
  dash_notifications: "Notificações",
  /* ProfileView */
  prof_reg_date: "Data de registro:", prof_country: "País, cidade:",
  prof_birthdate: "Data de nascimento:", prof_email: "E-mail:", prof_phone: "Telefone:",
  prof_upcoming: "Próximo evento", prof_event_subtitle: "20 outubro · Bogotá, Colômbia",
  prof_days: "dias", prof_hours: "horas", prof_min: "min", prof_seg: "seg",
  prof_day0: "Seg 20 Out", prof_day1: "Ter 21 Out", prof_day2: "Qua 22 Out", prof_day3: "Qui 23 Out",
  prof_no_tickets: "Sem ingressos",
  prof_no_tickets_sub: "Você ainda não está inscrito em nenhuma conferência do CONIITI 2026.",
  prof_explore: "Explorar conferências", prof_prev: "Anterior", prof_next_ticket: "Próximo",
  prof_edit: "Editar perfil", prof_loading: "Carregando…",
  /* InscritasView */
  iv_kpi_total: "Total inscritas", iv_kpi_confirmed: "Confirmadas",
  iv_kpi_ongoing: "Em andamento", iv_kpi_finished: "Finalizadas",
  iv_search_ph: "Buscar por conferência, palestrante, sala ou categoria...",
  iv_show_all: "Mostrar Todas", iv_conference_s: "conferência", iv_conference_pl: "conferências",
  iv_back_cats: "Voltar às Categorias", iv_no_results: "Nenhuma conferência encontrada",
  iv_matching: "correspondente a",
  iv_th_conference: "Conferência", iv_th_category: "Categoria", iv_th_status: "Status",
  iv_th_speaker: "Palestrante", iv_th_location: "Localização", iv_th_schedule: "Horário",
  iv_status_confirmed: "Confirmada", iv_status_ongoing: "Em andamento", iv_status_finished: "Finalizada",
  iv_cancel_action: "Cancelar inscrição", iv_loading: "Carregando suas conferências…",
  iv_empty_title: "Você ainda não tem conferências inscritas no CONIITI 2026",
  iv_empty_sub: "Explore a programação e inscreva-se nas suas favoritas!",
  iv_explore: "Explorar conferências", iv_no_results_cat: "Nenhuma conferência nesta categoria",
  iv_no_results_q: "Sem resultados para", iv_cancel_ok: "Inscrição em \"{0}\" cancelada",
  iv_cancel_fail: "Não foi possível cancelar a inscrição", iv_conn_error: "Erro de conexão",
  iv_load_error: "Não foi possível carregar as conferências",
  /* SettingsView */
  stv_tab_profile: "Dados do perfil", stv_tab_security: "Segurança", stv_tab_prefs: "Preferências",
  stv_field_name: "Nome completo", stv_field_phone: "Telefone",
  stv_field_city: "Cidade / País", stv_field_birthdate: "Data de nascimento",
  stv_save: "Salvar alterações", stv_saving: "Salvando…",
  stv_saved_ok: "Perfil atualizado com sucesso.",
  stv_save_error: "Não foi possível salvar. Verifique sua conexão.",
  stv_field_cur_pwd: "Senha atual", stv_field_new_pwd: "Nova senha",
  stv_field_confirm_pwd: "Confirmar nova senha",
  stv_pwd_min_hint: "Mínimo 6 caracteres", stv_pwd_repeat_hint: "Repita a senha",
  stv_update_pwd: "Atualizar senha", stv_updating: "Atualizando…",
  stv_pwd_ok: "Senha atualizada com sucesso.",
  stv_pwd_short: "A nova senha deve ter pelo menos 6 caracteres.",
  stv_pwd_mismatch: "As novas senhas não coincidem.",
  stv_pwd_error: "Não foi possível atualizar a senha.",
  stv_theme_title: "Tema da interface",
  stv_theme_light: "Claro UCC", stv_theme_light_desc: "Azul e branco institucional",
  stv_theme_dark: "Escuro UCC", stv_theme_dark_desc: "Modo noturno com acentos dourados",
  stv_theme_system: "Sistema", stv_theme_system_desc: "Segue a preferência do dispositivo",
  stv_compact_title: "Vista compacta",
  stv_compact_on: "Ativada — menos espaço entre elementos",
  stv_compact_off: "Desativada — espaçamento padrão",
  /* MessagesView */
  msv_loading: "Carregando mensagens…", msv_error: "Não foi possível carregar as mensagens.",
  msv_empty_title: "Sem mensagens",
  msv_empty_sub: "Quando o sistema enviar notificações, elas aparecerão aqui.",
  msv_heading: "Mensagens", msv_unread: "{0} não lidas", msv_mark_read: "Marcar como lida",
  msv_unread_label: "Não lida", msv_type_info: "Info", msv_type_alerta: "Alerta",
  msv_type_sistema: "Sistema",
  /* PlaceholderView */
  ph_favorites_title: "Favoritos", ph_favorites_msg: "Função de favoritos em breve.",
  ph_events_title: "Eventos", ph_completed_title: "Concluídas",
  ph_system_ready: "O sistema está pronto para receber estes dados na próxima fase do projeto.",
  ph_soon: "Em breve", ph_dev_title: "Seção em desenvolvimento",
  ph_dev_msg: "Esta funcionalidade estará disponível em breve.",
  /* Ticket */
  prof_ticket_sede: "LOCAL", prof_ticket_sala: "SALA", prof_ticket_serial: "SERIAL",
  prof_ticket_venue: "Universidad Católica de Colombia",
};

const FR: T = {
  home: "Accueil", nosotros: "À propos", ferias: "Nos Foires",
  inscripciones: "Inscriptions", noticias: "Actualités", ponentes: "Intervenants", login: "Connexion",
  register: "S'inscrire",
  buscar: "Rechercher...",
  hero_title: "Coniiti 2026", hero_country: "Pays invité : Italie",
  hero_speakers: "Conférenciers internationaux",
  stat_speakers: "Conférenciers", stat_sponsors: "Sponsors",
  stat_workshops: "Ateliers", stat_attendees: "Participants",
  stat_host: "Pays hôte", stat_days: "Jours d'événement",
  days: "Jours", hours: "Heures", minutes: "Minutes", seconds: "Secondes",
  card1_title: "Accueil", card1_p: "Explorez nos informations principales.",
  card2_title: "Nos Foires", card2_p: "Événements académiques et d'entreprise.",
  card3_title: "Inscriptions", card3_p: "Découvrez les étapes pour postuler.",
  card4_title: "Actualités", card4_p: "Restez informé.",
  nos_what: "Qu'est-ce que CONIITI ?",
  nos_what_p: "Le Congrès International d'Innovation et de Tendances en Ingénierie est l'événement académique phare de l'Université Catholique de Colombie. Dans sa XIIe édition, CONIITI 2026 accueille l'Italie comme pays invité.",
  nos_history: "Histoire",
  nos_history_p: "Depuis 2014, CONIITI est passé d'un événement national à un congrès présent dans plus de 20 pays.",
  nos_uni: "Université Organisatrice",
  nos_uni_p: "L'Université Catholique de Colombie, avec plus de 50 ans d'histoire et une accréditation de haute qualité, est le siège de CONIITI.",
  nos_visit: "Visiter le site officiel →",
  nos_goals: "Objectifs",
  goal1_t: "Internationalisation", goal1_p: "Échange de connaissances entre ingénieurs du monde entier.",
  goal2_t: "Innovation", goal2_p: "Dernières tendances technologiques et recherches appliquées.",
  goal3_t: "Networking", goal3_p: "Réseaux entre universitaires, entreprises et chercheurs.",
  goal4_t: "Formation", goal4_p: "Renforcement des compétences en ingénierie.",
  footer_center: "Centre de Conventions",
  footer_rights: "© 2026 CONIITI - Tous droits réservés",
  back: "Retour à l'accueil",
  hero_edition: "XIIe Édition · Bogotá, Colombie",
  hero_tagline: "Le congrès international qui connecte l'ingénierie du futur.",
  hero_cta: "S'inscrire au congrès",
  hero_city: "Bogotá, Colombie",
  hero_date: "23 septembre 2026",
  hero_guest: "Pays invité",
  countdown_label: "Le congrès commence dans",
  home_discover: "Découvrez CONIITI 2026",
  home_discover_sub: "Explorez chaque recoin du congrès international d'ingénierie",
  insc_title: "Conférences CONIITI 2026",
  insc_sub: "Parcourez le catalogue et inscrivez-vous aux conférences qui vous intéressent",
  insc_search_ph: "Rechercher par titre, intervenant ou thème…",
  insc_loading: "Chargement des conférences…",
  insc_retry: "Réessayer",
  insc_empty: "Aucune conférence trouvée avec ces filtres.",
  insc_spots_none: "Plus de places disponibles",
  insc_spots: "place disponible",
  insc_spots_pl: "places disponibles",
  insc_register: "M'inscrire",
  insc_cancel: "Annuler l'inscription",
  insc_registering: "Inscription en cours…",
  insc_cancelling: "Annulation…",
  insc_full: "Complet",
  insc_registered_badge: "Inscrit",
  insc_to_define: "À définir",
  /* Dashboard nav */
  dash_profile: "Profil", dash_conferences: "Mes conférences", dash_completed: "Terminées",
  dash_events: "Événements", dash_favorites: "Favoris", dash_calendar: "Calendrier",
  dash_messages: "Messages", dash_settings: "Paramètres", dash_logout: "Se déconnecter",
  dash_mobile_talks: "Mes conférences", dash_go_home: "Accueil", dash_loading: "Chargement…",
  dash_welcome_back: "Bon retour,", dash_welcome_first: "Bienvenue au CONIITI 2026 !",
  dash_notifications: "Notifications",
  /* ProfileView */
  prof_reg_date: "Date d'inscription :", prof_country: "Pays, ville :",
  prof_birthdate: "Date de naissance :", prof_email: "E-mail :", prof_phone: "Téléphone :",
  prof_upcoming: "Prochain événement", prof_event_subtitle: "20 octobre · Bogotá, Colombie",
  prof_days: "jours", prof_hours: "heures", prof_min: "min", prof_seg: "sec",
  prof_day0: "Lun 20 Oct", prof_day1: "Mar 21 Oct", prof_day2: "Mer 22 Oct", prof_day3: "Jeu 23 Oct",
  prof_no_tickets: "Pas de billets",
  prof_no_tickets_sub: "Vous n'êtes pas encore inscrit à une conférence du CONIITI 2026.",
  prof_explore: "Explorer les conférences", prof_prev: "Précédent", prof_next_ticket: "Suivant",
  prof_edit: "Modifier le profil", prof_loading: "Chargement…",
  /* InscritasView */
  iv_kpi_total: "Total inscrites", iv_kpi_confirmed: "Confirmées",
  iv_kpi_ongoing: "En cours", iv_kpi_finished: "Terminées",
  iv_search_ph: "Rechercher par conférence, intervenant, salle ou catégorie...",
  iv_show_all: "Afficher Toutes", iv_conference_s: "conférence", iv_conference_pl: "conférences",
  iv_back_cats: "Retour aux Catégories", iv_no_results: "Aucune conférence trouvée",
  iv_matching: "correspondant à",
  iv_th_conference: "Conférence", iv_th_category: "Catégorie", iv_th_status: "Statut",
  iv_th_speaker: "Intervenant", iv_th_location: "Lieu", iv_th_schedule: "Horaire",
  iv_status_confirmed: "Confirmée", iv_status_ongoing: "En cours", iv_status_finished: "Terminée",
  iv_cancel_action: "Annuler l'inscription", iv_loading: "Chargement de vos conférences…",
  iv_empty_title: "Vous n'avez pas encore de conférences au CONIITI 2026",
  iv_empty_sub: "Explorez le programme et inscrivez-vous à vos préférées !",
  iv_explore: "Explorer les conférences", iv_no_results_cat: "Aucune conférence dans cette catégorie",
  iv_no_results_q: "Aucun résultat pour", iv_cancel_ok: "Inscription à \"{0}\" annulée",
  iv_cancel_fail: "Impossible d'annuler l'inscription", iv_conn_error: "Erreur de connexion",
  iv_load_error: "Impossible de charger les conférences",
  /* SettingsView */
  stv_tab_profile: "Données du profil", stv_tab_security: "Sécurité", stv_tab_prefs: "Préférences",
  stv_field_name: "Nom complet", stv_field_phone: "Téléphone",
  stv_field_city: "Ville / Pays", stv_field_birthdate: "Date de naissance",
  stv_save: "Enregistrer les modifications", stv_saving: "Enregistrement…",
  stv_saved_ok: "Profil mis à jour avec succès.",
  stv_save_error: "Impossible d'enregistrer. Vérifiez votre connexion.",
  stv_field_cur_pwd: "Mot de passe actuel", stv_field_new_pwd: "Nouveau mot de passe",
  stv_field_confirm_pwd: "Confirmer le nouveau mot de passe",
  stv_pwd_min_hint: "Minimum 6 caractères", stv_pwd_repeat_hint: "Répétez le mot de passe",
  stv_update_pwd: "Mettre à jour le mot de passe", stv_updating: "Mise à jour…",
  stv_pwd_ok: "Mot de passe mis à jour avec succès.",
  stv_pwd_short: "Le nouveau mot de passe doit comporter au moins 6 caractères.",
  stv_pwd_mismatch: "Les nouveaux mots de passe ne correspondent pas.",
  stv_pwd_error: "Impossible de mettre à jour le mot de passe.",
  stv_theme_title: "Thème de l'interface",
  stv_theme_light: "Clair UCC", stv_theme_light_desc: "Bleu et blanc institutionnel",
  stv_theme_dark: "Sombre UCC", stv_theme_dark_desc: "Mode nuit avec accents dorés",
  stv_theme_system: "Système", stv_theme_system_desc: "Suit les préférences de l'appareil",
  stv_compact_title: "Vue compacte",
  stv_compact_on: "Activée — moins d'espace entre les éléments",
  stv_compact_off: "Désactivée — espacement standard",
  /* MessagesView */
  msv_loading: "Chargement des messages…", msv_error: "Impossible de charger les messages.",
  msv_empty_title: "Pas de messages",
  msv_empty_sub: "Lorsque le système vous enverra des notifications, elles apparaîtront ici.",
  msv_heading: "Messages", msv_unread: "{0} non lus", msv_mark_read: "Marquer comme lu",
  msv_unread_label: "Non lu", msv_type_info: "Info", msv_type_alerta: "Alerte",
  msv_type_sistema: "Système",
  /* PlaceholderView */
  ph_favorites_title: "Favoris", ph_favorites_msg: "Fonctionnalité favoris bientôt disponible.",
  ph_events_title: "Événements", ph_completed_title: "Terminées",
  ph_system_ready: "Le système est prêt à recevoir ces données lors de la prochaine phase du projet.",
  ph_soon: "Bientôt", ph_dev_title: "Section en développement",
  ph_dev_msg: "Cette fonctionnalité sera disponible prochainement.",
  /* Ticket */
  prof_ticket_sede: "LIEU", prof_ticket_sala: "SALLE", prof_ticket_serial: "SÉRIE",
  prof_ticket_venue: "Universidad Católica de Colombia",
};

export const TRANSLATIONS: Record<LangCode, T> = { ES, EN, IT, PT, FR };

interface LanguageContextType {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: T;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ES", setLang: () => {}, t: ES,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(
    () => (localStorage.getItem("lang") as LangCode) || "ES"
  );
  const setLang = (l: LangCode) => { setLangState(l); localStorage.setItem("lang", l); };
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: TRANSLATIONS[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
