import { createContext, useContext, useState, ReactNode } from "react";

export type LangCode = "ES" | "EN" | "IT" | "PT" | "FR";

export const LANGUAGES: { code: LangCode; flag: string; name: string }[] = [
  { code: "ES", flag: "🇪🇸", name: "Español"   },
  { code: "EN", flag: "🇺🇸", name: "English"   },
  { code: "IT", flag: "🇮🇹", name: "Italiano"  },
  { code: "PT", flag: "🇧🇷", name: "Português" },
  { code: "FR", flag: "🇫🇷", name: "Français"  },
];

type T = Record<string, string>;

const ES: T = {
  /* Navbar */
  home: "Home", nosotros: "Nosotros", ferias: "Nuestras ferias",
  inscripciones: "Conferencias", noticias: "Noticias", ponentes: "Ponentes", login: "Ingresar",
  register: "Crear cuenta",
  buscar: "Buscar...",
  /* Hero */
  hero_title: "Coniiti 2026", hero_country: "País invitado: Italia",
  hero_speakers: "Conferencistas internacionales",
  /* Stats */
  stat_speakers: "Conferencistas", stat_sponsors: "Patrocinadores",
  stat_workshops: "Talleres", stat_attendees: "Participantes",
  stat_host: "País anfitrión", stat_days: "Días de evento",
  /* Countdown */
  days: "Días", hours: "Horas", minutes: "Minutos", seconds: "Segundos",
  /* Tarjetas Home */
  card1_title: "Home", card1_p: "Explora nuestra información principal.",
  card2_title: "Nuestras Ferias", card2_p: "Eventos académicos y empresariales.",
  card3_title: "Conferencias", card3_p: "Explora y regístrate en las charlas del evento.",
  card4_title: "Noticias", card4_p: "Mantente informado.",
  /* Nosotros */
  nos_what: "¿Qué es CONIITI?",
  nos_what_p: "El Congreso Internacional de Innovación y Tendencias en Ingeniería es el evento académico insignia de la Universidad Católica de Colombia. En su XII edición, CONIITI 2026 tiene como país invitado a Italia.",
  nos_history: "Historia",
  nos_history_p: "Desde 2014, CONIITI ha crecido de un evento nacional a un congreso con presencia en más de 20 países. Cada edición ha impulsado la publicación de investigaciones indexadas y el fortalecimiento de redes internacionales.",
  nos_uni: "Universidad Organizadora",
  nos_uni_p: "La Universidad Católica de Colombia, con más de 50 años de historia y acreditación de alta calidad, es la sede y alma de CONIITI. Su Facultad de Ingeniería lidera cada edición con rigor académico y visión global.",
  nos_visit: "Visitar sitio oficial →",
  nos_goals: "Objetivos",
  goal1_t: "Internacionalización", goal1_p: "Intercambio de conocimiento entre ingenieros del mundo.",
  goal2_t: "Innovación", goal2_p: "Últimas tendencias tecnológicas e investigaciones aplicadas.",
  goal3_t: "Networking", goal3_p: "Redes entre académicos, empresas e investigadores.",
  goal4_t: "Formación", goal4_p: "Fortalecimiento de competencias en ingeniería.",
  /* Ferias */
  fer_hero_tag: "XII Edición · 2026",
  fer_hero_sub: "Congreso Internacional de Innovación y Tendencias en Ingeniería",
  fer_mission_label: "Nuestra Misión",
  fer_mission_q: "Un espacio abierto de interacción entre actores del ecosistema de innovación, orientado a compartir nuevos enfoques para la transformación creativa de Colombia a través de soluciones de ingeniería.",
  fer_stat_editions: "Ediciones", fer_stat_countries: "Países",
  fer_stat_participants: "Participantes", fer_stat_spk: "Conferencistas",
  fer_editions_title: "Ediciones del Congreso",
  fer_editions_sub: "Explora la historia de cada edición de CONIITI.",
  fer_card_2015: "Ver información del evento.",
  fer_coming_soon: "Próximamente",
  fer_why: "¿Por qué asistir?",
  fer_timeline: "Trayectoria del Congreso",
  fer_tl_2014: "Primera edición nacional en la Universidad Católica de Colombia, sentando las bases del congreso.",
  fer_tl_2016: "Apertura internacional con ponencias de ingenieros de América Latina y España.",
  fer_tl_2019: "Consolidación académica con indexación de memorias en bases de datos internacionales.",
  fer_tl_2020: "Adaptación al formato virtual, conectando a participantes en más de 15 países.",
  fer_tl_2025: "XI edición: 452+ participantes, 35 conferencistas y 5 talleres especializados.",
  fer_tl_2026: "XII edición con Italia como país invitado en formato híbrido desde Bogotá.",
  fer_dates_title: "Fechas Clave — 2026",
  fer_date1_val: "30 Jun 2026", fer_date1_label: "Envío de artículos",
  fer_date2_val: "18 Ago 2026", fer_date2_label: "Notificación de aceptación",
  fer_date3_val: "30 Sep – 2 Oct", fer_date3_label: "Evento híbrido",
  fer_includes: "Tu inscripción incluye",
  fer_inc1: "Registro como conferencista",
  fer_inc2: "Certificado oficial de participación",
  fer_inc3: "Publicación en memorias científicas",
  fer_modalities: "¿Cómo participar?",
  fer_modal_local: "Presencial",
  fer_modal_local_desc: "Universidad Católica de Colombia, Sede 4, Bogotá, Colombia",
  fer_modal_virtual: "Virtual",
  fer_modal_virtual_desc: "Transmisión en vivo para participantes de todo el mundo",
  fer_partners_title: "Aliados Estratégicos",
  fer_contact_title: "Contáctanos",
  fer_contact_email_l: "Correo electrónico",
  fer_contact_phone_l: "Teléfono",
  fer_contact_addr_l: "Sede",
  fer_cta_title: "CONIITI 2026 te espera",
  fer_format: "Bogotá, Colombia · Formato Híbrido",
  fer_cta_btn: "Inscríbete en CONIITI 2026",
  /* Footer */
  footer_center: "Centro de Convenciones",
  footer_rights: "© 2026 CONIITI - Todos los derechos reservados",
  /* Login */
  back: "Volver al inicio",
  /* Dashboard nav */
  dash_profile: "Perfil", dash_conferences: "Mis conferencias", dash_completed: "Completadas",
  dash_favorites: "Favoritos", dash_calendar: "Calendario",
  dash_messages: "Mensajes", dash_settings: "Ajustes", dash_logout: "Cerrar sesión",
  dash_mobile_talks: "Mis charlas", dash_go_home: "Inicio", dash_loading: "Cargando…",
  dash_welcome_back: "Bienvenido de nuevo,", dash_welcome_first: "¡Bienvenido al CONIITI 2026!",
  dash_notifications: "Notificaciones",
  dash_account_settings: "Ajustes de cuenta", dash_section_account: "Cuenta",
  /* ProfileView */
  prof_reg_date: "Fecha de registro:", prof_country: "País, ciudad:",
  prof_birthdate: "Fecha de nacimiento:", prof_email: "E-mail:", prof_phone: "Teléfono:",
  prof_upcoming: "Próximo evento", prof_event_subtitle: "20 octubre · Bogotá, Colombia",
  prof_days: "días", prof_hours: "horas", prof_min: "min", prof_seg: "seg",
  prof_day0: "Lun 20 Oct", prof_day1: "Mar 21 Oct", prof_day2: "Mié 22 Oct", prof_day3: "Jue 23 Oct",
  prof_no_tickets: "Sin entradas",
  prof_no_tickets_sub: "Aún no estás inscrito en ninguna conferencia del CONIITI 2026.",
  prof_explore: "Explorar conferencias", prof_prev: "Anterior", prof_next_ticket: "Siguiente",
  prof_edit: "Editar perfil", prof_loading: "Cargando…",
  /* InscritasView */
  iv_kpi_total: "Total inscritas", iv_kpi_confirmed: "Confirmadas",
  iv_kpi_ongoing: "En curso", iv_kpi_finished: "Finalizadas",
  iv_search_ph: "Buscar por conferencia, ponente, salón o categoría...",
  iv_show_all: "Mostrar Todas", iv_conference_s: "conferencia", iv_conference_pl: "conferencias",
  iv_back_cats: "Volver a Categorías", iv_no_results: "No se encontraron conferencias",
  iv_matching: "que coincidan con",
  iv_th_conference: "Conferencia", iv_th_category: "Categoría", iv_th_status: "Estado",
  iv_th_speaker: "Ponente", iv_th_location: "Ubicación", iv_th_schedule: "Horario",
  iv_status_confirmed: "Confirmada", iv_status_ongoing: "En curso", iv_status_finished: "Finalizada",
  iv_cancel_action: "Cancelar inscripción", iv_loading: "Cargando tus conferencias…",
  iv_empty_title: "Aún no tienes conferencias inscritas en la CONIITI 2026",
  iv_empty_sub: "¡Explora el cronograma e inscríbete a tus favoritas!",
  iv_explore: "Explorar conferencias", iv_no_results_cat: "No hay conferencias en esta categoría",
  iv_no_results_q: "Sin resultados para", iv_cancel_ok: "Inscripción a \"{0}\" cancelada",
  iv_cancel_fail: "No se pudo cancelar la inscripción", iv_conn_error: "Error de conexión",
  iv_load_error: "No se pudieron cargar las conferencias",
  /* SettingsView */
  stv_tab_profile: "Datos de perfil", stv_tab_security: "Seguridad", stv_tab_prefs: "Preferencias",
  stv_field_name: "Nombre completo", stv_field_phone: "Teléfono",
  stv_field_city: "Ciudad / País", stv_field_birthdate: "Fecha de nacimiento",
  stv_save: "Guardar cambios", stv_saving: "Guardando…",
  stv_saved_ok: "Perfil actualizado correctamente.",
  stv_save_error: "No se pudo guardar. Verifica tu conexión.",
  stv_field_cur_pwd: "Contraseña actual", stv_field_new_pwd: "Nueva contraseña",
  stv_field_confirm_pwd: "Confirmar nueva contraseña",
  stv_pwd_min_hint: "Mínimo 6 caracteres", stv_pwd_repeat_hint: "Repite la contraseña",
  stv_update_pwd: "Actualizar contraseña", stv_updating: "Actualizando…",
  stv_pwd_ok: "Contraseña actualizada correctamente.",
  stv_pwd_short: "La nueva contraseña debe tener al menos 6 caracteres.",
  stv_pwd_mismatch: "Las contraseñas nuevas no coinciden.",
  stv_pwd_error: "No se pudo actualizar la contraseña.",
  stv_theme_title: "Tema de la interfaz",
  stv_theme_light: "Claro UCC", stv_theme_light_desc: "Azul y blanco institucional",
  stv_theme_dark: "Oscuro UCC", stv_theme_dark_desc: "Modo nocturno con acentos dorados",
  stv_theme_system: "Sistema", stv_theme_system_desc: "Sigue la preferencia del dispositivo",
  stv_compact_title: "Vista compacta",
  stv_compact_on: "Activada — menos espacio entre elementos",
  stv_compact_off: "Desactivada — espaciado estándar",
  stv_avatar_change: "Cambiar foto de perfil",
  stv_2fa_title: "Autenticación de Dos Factores (2FA)",
  stv_2fa_desc: "Aumenta la seguridad de tu cuenta solicitando un código de verificación en cada inicio de sesión.",
  stv_2fa_enabled: "2FA activado",
  stv_2fa_disabled: "2FA desactivado",
  stv_sessions_title: "Sesiones activas",
  stv_session_badge: "Sesión activa",
  stv_notif_title: "Notificaciones",
  stv_notif_conf: "Confirmaciones de inscripción a conferencias",
  stv_notif_cancel: "Alertas de conferencias canceladas o modificadas",
  stv_timefmt_title: "Formato de hora",
  stv_timefmt_12: "12 horas (AM/PM)",
  stv_timefmt_24: "24 horas (Militar)",
  /* MessagesView */
  msv_loading: "Cargando mensajes…", msv_error: "No se pudieron cargar los mensajes.",
  msv_empty_title: "Sin mensajes",
  msv_empty_sub: "Cuando el sistema te envíe notificaciones, aparecerán aquí.",
  msv_heading: "Mensajes", msv_unread: "{0} sin leer", msv_mark_read: "Marcar como leído",
  msv_unread_label: "No leído", msv_type_info: "Info", msv_type_alerta: "Alerta",
  msv_type_sistema: "Sistema",
  msv_center_title: "Centro de Notificaciones",
  msv_tab_all: "Todas", msv_tab_unread: "No leídas",
  msv_mark_all_read: "Marcar todas como leídas",
  msv_empty_notif: "No tienes notificaciones pendientes por aquí.",
  msv_time_now: "Ahora", msv_time_min: "Hace {0} min", msv_time_hour: "Hace {0} h",
  msv_time_today: "Hoy, {0}", msv_time_yesterday: "Ayer, {0}",
  msv_back_inbox: "Volver a recibidos", msv_label_inbox: "Recibidos",
  msv_to_me: "para mí",
  msv_ticket_label: "Pase de ingreso", msv_ticket_access: "Acceso confirmado",
  msv_reply_close: "Responder (Cerrar)", msv_mark_unread: "Marcar como no leído",
  msv_adv_search: "Búsqueda avanzada", msv_adv_date_range: "Rango de fechas",
  msv_adv_today: "Hoy", msv_adv_week: "Última semana",
  msv_adv_from: "Desde", msv_adv_to: "Hasta",
  msv_adv_theme: "Línea temática", msv_adv_theme_all: "Todas las líneas",
  msv_adv_keyword: "Palabra clave", msv_adv_keyword_ph: "Buscar en el cuerpo del mensaje...",
  msv_adv_clear: "Limpiar filtros", msv_adv_apply: "Aplicar filtros",
  msv_adv_no_results: "No se encontraron notificaciones con esos filtros.",
  /* PlaceholderView */
  ph_favorites_title: "Favoritos", ph_favorites_msg: "Función de favoritos próximamente disponible.",
  ph_completed_title: "Completadas",
  ph_system_ready: "El sistema está listo para recibir estos datos en la siguiente fase del proyecto.",
  ph_soon: "Próximamente", ph_dev_title: "Sección en desarrollo",
  ph_dev_msg: "Esta funcionalidad estará disponible próximamente.",
  /* CompletedConferencesView */
  ccv_heading: "Historial de Asistencia",
  ccv_search_ph: "Buscar por conferencia o ponente...",
  ccv_th_conference: "Nombre de Conferencia", ccv_th_speaker: "Ponente",
  ccv_th_location: "Ubicación", ccv_th_date: "Fecha", ccv_th_action: "Acción",
  ccv_cert_btn: "Descargar Certificado",
  ccv_loading: "Cargando historial…", ccv_load_error: "No se pudo cargar el historial",
  ccv_empty_title: "Aún no registras asistencias a conferencias finalizadas.",
  ccv_empty_sub: "Recuerda escanear tu código QR al ingresar al aula.",
  ccv_showing: "Mostrando registros", ccv_no_results: "Sin resultados para esta búsqueda",
  ccv_filter_label: "Categoría", ccv_filter_all: "Todas",
  ccv_sort_by: "Ordenar", ccv_sort_newest: "Más recientes", ccv_sort_oldest: "Más antiguas",
  /* Ticket */
  prof_ticket_sede: "SEDE", prof_ticket_sala: "SALA", prof_ticket_serial: "SERIAL",
  prof_ticket_venue: "Universidad Católica de Colombia",
  /* Home hardcoded */
  hero_edition: "XII Edición · Bogotá, Colombia",
  hero_tagline: "El congreso internacional que conecta la ingeniería del futuro.",
  hero_cta: "Inscríbete al congreso",
  hero_city: "Bogotá, Colombia",
  hero_date: "23 de septiembre, 2026",
  hero_guest: "País invitado",
  countdown_label: "El congreso comienza en",
  home_discover: "Descubre CONIITI 2026",
  home_discover_sub: "Explora cada rincón del congreso internacional de ingeniería",
  /* Inscripciones */
  insc_title: "Conferencias CONIITI 2026",
  insc_sub: "Explora el catálogo de charlas y regístrate en las que más te interesen",
  insc_search_ph: "Buscar por título, ponente o tema…",
  insc_loading: "Cargando conferencias…",
  insc_retry: "Reintentar",
  insc_empty: "No se encontraron conferencias con esos filtros.",
  insc_spots_none: "Sin cupos disponibles",
  insc_spots: "cupo disponible",
  insc_spots_pl: "cupos disponibles",
  insc_register: "Inscribirme",
  insc_cancel: "Cancelar inscripción",
  insc_registering: "Inscribiendo…",
  insc_cancelling: "Cancelando…",
  insc_full: "Sin cupos",
  insc_registered_badge: "Inscrito",
  insc_to_define: "Por definir",
  /* Categorías oficiales */
  cat_software: "Ingeniería de Software y Sistemas de Información",
  cat_ai:       "Inteligencia Artificial y Co-existencia",
  cat_cities:   "Ciudades Inteligentes y Desarrollo Sostenible",
  cat_security: "Seguridad, Privacidad e Infraestructura",
  cat_tech:     "Tecnología, Sociedad e Innovación",
};

const EN: T = {
  /* Dashboard nav */
  dash_profile: "Profile", dash_conferences: "My Conferences", dash_completed: "Completed",
  dash_favorites: "Favorites", dash_calendar: "Calendar",
  dash_messages: "Messages", dash_settings: "Settings", dash_logout: "Log out",
  dash_mobile_talks: "My talks", dash_go_home: "Home", dash_loading: "Loading…",
  dash_welcome_back: "Welcome back,", dash_welcome_first: "Welcome to CONIITI 2026!",
  dash_notifications: "Notifications",
  dash_account_settings: "Account settings", dash_section_account: "Account",
  /* ProfileView */
  prof_reg_date: "Registration date:", prof_country: "Country, city:",
  prof_birthdate: "Date of birth:", prof_email: "E-mail:", prof_phone: "Phone:",
  prof_upcoming: "Upcoming event", prof_event_subtitle: "October 20 · Bogotá, Colombia",
  prof_days: "days", prof_hours: "hours", prof_min: "min", prof_seg: "sec",
  prof_day0: "Mon Oct 20", prof_day1: "Tue Oct 21", prof_day2: "Wed Oct 22", prof_day3: "Thu Oct 23",
  prof_no_tickets: "No tickets",
  prof_no_tickets_sub: "You are not yet registered for any conference at CONIITI 2026.",
  prof_explore: "Explore conferences", prof_prev: "Previous", prof_next_ticket: "Next",
  prof_edit: "Edit profile", prof_loading: "Loading…",
  /* InscritasView */
  iv_kpi_total: "Total registered", iv_kpi_confirmed: "Confirmed",
  iv_kpi_ongoing: "Ongoing", iv_kpi_finished: "Finished",
  iv_search_ph: "Search by conference, speaker, room or category...",
  iv_show_all: "Show All", iv_conference_s: "conference", iv_conference_pl: "conferences",
  iv_back_cats: "Back to Categories", iv_no_results: "No conferences found",
  iv_matching: "matching",
  iv_th_conference: "Conference", iv_th_category: "Category", iv_th_status: "Status",
  iv_th_speaker: "Speaker", iv_th_location: "Location", iv_th_schedule: "Schedule",
  iv_status_confirmed: "Confirmed", iv_status_ongoing: "Ongoing", iv_status_finished: "Finished",
  iv_cancel_action: "Cancel registration", iv_loading: "Loading your conferences…",
  iv_empty_title: "You have no conferences registered at CONIITI 2026 yet",
  iv_empty_sub: "Explore the schedule and register for your favorites!",
  iv_explore: "Explore conferences", iv_no_results_cat: "No conferences in this category",
  iv_no_results_q: "No results for", iv_cancel_ok: "Registration for \"{0}\" cancelled",
  iv_cancel_fail: "Could not cancel the registration", iv_conn_error: "Connection error",
  iv_load_error: "Could not load conferences",
  /* SettingsView */
  stv_tab_profile: "Profile data", stv_tab_security: "Security", stv_tab_prefs: "Preferences",
  stv_field_name: "Full name", stv_field_phone: "Phone",
  stv_field_city: "City / Country", stv_field_birthdate: "Date of birth",
  stv_save: "Save changes", stv_saving: "Saving…",
  stv_saved_ok: "Profile updated successfully.",
  stv_save_error: "Could not save. Check your connection.",
  stv_field_cur_pwd: "Current password", stv_field_new_pwd: "New password",
  stv_field_confirm_pwd: "Confirm new password",
  stv_pwd_min_hint: "Minimum 6 characters", stv_pwd_repeat_hint: "Repeat the password",
  stv_update_pwd: "Update password", stv_updating: "Updating…",
  stv_pwd_ok: "Password updated successfully.",
  stv_pwd_short: "The new password must be at least 6 characters.",
  stv_pwd_mismatch: "The new passwords do not match.",
  stv_pwd_error: "Could not update the password.",
  stv_theme_title: "Interface theme",
  stv_theme_light: "Light UCC", stv_theme_light_desc: "Institutional blue and white",
  stv_theme_dark: "Dark UCC", stv_theme_dark_desc: "Night mode with golden accents",
  stv_theme_system: "System", stv_theme_system_desc: "Follows device preference",
  stv_compact_title: "Compact view",
  stv_compact_on: "Enabled — less space between elements",
  stv_compact_off: "Disabled — standard spacing",
  stv_avatar_change: "Change profile photo",
  stv_2fa_title: "Two-Factor Authentication (2FA)",
  stv_2fa_desc: "Increase account security by requiring a verification code at each login.",
  stv_2fa_enabled: "2FA enabled",
  stv_2fa_disabled: "2FA disabled",
  stv_sessions_title: "Active sessions",
  stv_session_badge: "Active session",
  stv_notif_title: "Notifications",
  stv_notif_conf: "Conference registration confirmations",
  stv_notif_cancel: "Cancelled or modified conference alerts",
  stv_timefmt_title: "Time format",
  stv_timefmt_12: "12 hours (AM/PM)",
  stv_timefmt_24: "24 hours (Military)",
  /* MessagesView */
  msv_loading: "Loading messages…", msv_error: "Could not load messages.",
  msv_empty_title: "No messages",
  msv_empty_sub: "When the system sends you notifications, they will appear here.",
  msv_heading: "Messages", msv_unread: "{0} unread", msv_mark_read: "Mark as read",
  msv_unread_label: "Unread", msv_type_info: "Info", msv_type_alerta: "Alert",
  msv_type_sistema: "System",
  msv_center_title: "Notification Center",
  msv_tab_all: "All", msv_tab_unread: "Unread",
  msv_mark_all_read: "Mark all as read",
  msv_empty_notif: "No pending notifications here.",
  msv_time_now: "Just now", msv_time_min: "{0} min ago", msv_time_hour: "{0} h ago",
  msv_time_today: "Today, {0}", msv_time_yesterday: "Yesterday, {0}",
  msv_back_inbox: "Back to inbox", msv_label_inbox: "Inbox",
  msv_to_me: "to me",
  msv_ticket_label: "Entry pass", msv_ticket_access: "Confirmed access",
  msv_reply_close: "Reply (Close)", msv_mark_unread: "Mark as unread",
  msv_adv_search: "Advanced search", msv_adv_date_range: "Date range",
  msv_adv_today: "Today", msv_adv_week: "Last week",
  msv_adv_from: "From", msv_adv_to: "To",
  msv_adv_theme: "Thematic line", msv_adv_theme_all: "All lines",
  msv_adv_keyword: "Keyword", msv_adv_keyword_ph: "Search in message body...",
  msv_adv_clear: "Clear filters", msv_adv_apply: "Apply filters",
  msv_adv_no_results: "No notifications found with those filters.",
  /* PlaceholderView */
  ph_favorites_title: "Favorites", ph_favorites_msg: "Favorites feature coming soon.",
  ph_completed_title: "Completed",
  ph_system_ready: "The system is ready to receive this data in the next project phase.",
  ph_soon: "Coming soon", ph_dev_title: "Section under development",
  ph_dev_msg: "This functionality will be available soon.",
  /* CompletedConferencesView */
  ccv_heading: "Attendance History",
  ccv_search_ph: "Search by conference or speaker...",
  ccv_th_conference: "Conference Name", ccv_th_speaker: "Speaker",
  ccv_th_location: "Location", ccv_th_date: "Date", ccv_th_action: "Action",
  ccv_cert_btn: "Download Certificate",
  ccv_loading: "Loading history…", ccv_load_error: "Could not load attendance history",
  ccv_empty_title: "No completed conference attendance on record.",
  ccv_empty_sub: "Remember to scan your QR code when entering the room.",
  ccv_showing: "Showing records", ccv_no_results: "No results for this search",
  ccv_filter_label: "Category", ccv_filter_all: "All",
  ccv_sort_by: "Sort by", ccv_sort_newest: "Newest", ccv_sort_oldest: "Oldest",

  home: "Home", nosotros: "About Us", ferias: "Our Fairs",
  inscripciones: "Conferences", noticias: "News", ponentes: "Speakers", login: "Login",
  register: "Sign Up",
  buscar: "Search...",
  hero_title: "Coniiti 2026", hero_country: "Guest Country: Italy",
  hero_speakers: "International Speakers",
  stat_speakers: "Speakers", stat_sponsors: "Sponsors",
  stat_workshops: "Workshops", stat_attendees: "Attendees",
  stat_host: "Host Country", stat_days: "Event Days",
  days: "Days", hours: "Hours", minutes: "Minutes", seconds: "Seconds",
  card1_title: "Home", card1_p: "Explore our main information.",
  card2_title: "Our Fairs", card2_p: "Academic and business events.",
  card3_title: "Registrations", card3_p: "Learn the steps to apply.",
  card4_title: "News", card4_p: "Stay informed.",
  nos_what: "What is CONIITI?",
  nos_what_p: "The International Congress of Innovation and Trends in Engineering is the flagship academic event of Universidad Católica de Colombia. In its XII edition, CONIITI 2026 welcomes Italy as guest country.",
  nos_history: "History",
  nos_history_p: "Since 2014, CONIITI has grown from a national event to a congress with presence in more than 20 countries. Each edition has driven the publication of indexed research and the strengthening of international networks.",
  nos_uni: "Organizing University",
  nos_uni_p: "Universidad Católica de Colombia, with more than 50 years of history and high quality accreditation, is the home of CONIITI. Its Faculty of Engineering leads each edition with academic rigor and global vision.",
  nos_visit: "Visit official site →",
  nos_goals: "Goals",
  goal1_t: "Internationalization", goal1_p: "Knowledge exchange among engineers worldwide.",
  goal2_t: "Innovation", goal2_p: "Latest technological trends and applied research.",
  goal3_t: "Networking", goal3_p: "Networks among academics, companies and researchers.",
  goal4_t: "Training", goal4_p: "Strengthening engineering competencies.",
  fer_hero_tag: "XII Edition · 2026",
  fer_hero_sub: "International Congress on Innovation and Trends in Engineering",
  fer_mission_label: "Our Mission",
  fer_mission_q: "An open space for interaction between innovation ecosystem actors, aimed at sharing new approaches for the creative transformation of Colombia through engineering-oriented solutions.",
  fer_stat_editions: "Editions", fer_stat_countries: "Countries",
  fer_stat_participants: "Participants", fer_stat_spk: "Speakers",
  fer_editions_title: "Congress Editions",
  fer_editions_sub: "Explore the history of each CONIITI edition.",
  fer_card_2015: "View event information.",
  fer_coming_soon: "Coming Soon",
  fer_why: "Why Attend?",
  fer_timeline: "Congress Journey",
  fer_tl_2014: "First national edition at Universidad Católica de Colombia, laying the congress foundations.",
  fer_tl_2016: "International opening with presentations from engineers across Latin America and Spain.",
  fer_tl_2019: "Academic consolidation with indexing of proceedings in international databases.",
  fer_tl_2020: "Adaptation to virtual format, connecting participants from over 15 countries.",
  fer_tl_2025: "XI edition: 452+ participants, 35 speakers and 5 specialized workshops.",
  fer_tl_2026: "XII edition with Italy as guest country in hybrid format from Bogotá.",
  fer_dates_title: "Key Dates — 2026",
  fer_date1_val: "Jun 30, 2026", fer_date1_label: "Article submission",
  fer_date2_val: "Aug 18, 2026", fer_date2_label: "Acceptance notification",
  fer_date3_val: "Sep 30 – Oct 2", fer_date3_label: "Hybrid event",
  fer_includes: "Your registration includes",
  fer_inc1: "Speaker registration",
  fer_inc2: "Official participation certificate",
  fer_inc3: "Publication in scientific proceedings",
  fer_modalities: "How to Participate?",
  fer_modal_local: "In-Person",
  fer_modal_local_desc: "Universidad Católica de Colombia, Campus 4, Bogotá, Colombia",
  fer_modal_virtual: "Virtual",
  fer_modal_virtual_desc: "Live stream for participants worldwide",
  fer_partners_title: "Strategic Partners",
  fer_contact_title: "Contact Us",
  fer_contact_email_l: "Email",
  fer_contact_phone_l: "Phone",
  fer_contact_addr_l: "Venue",
  fer_cta_title: "CONIITI 2026 awaits you",
  fer_format: "Bogotá, Colombia · Hybrid Format",
  fer_cta_btn: "Register for CONIITI 2026",
  footer_center: "Convention Center",
  footer_rights: "© 2026 CONIITI - All rights reserved",
  back: "Back to home",
  hero_edition: "XII Edition · Bogotá, Colombia",
  hero_tagline: "The international congress connecting the engineering of the future.",
  hero_cta: "Register for the congress",
  hero_city: "Bogotá, Colombia",
  hero_date: "September 23, 2026",
  hero_guest: "Guest country",
  countdown_label: "The congress begins in",
  home_discover: "Discover CONIITI 2026",
  home_discover_sub: "Explore every corner of the international engineering congress",
  insc_title: "CONIITI 2026 Conferences",
  insc_sub: "Browse the talk catalogue and register for the ones you find most interesting",
  insc_search_ph: "Search by title, speaker or topic…",
  insc_loading: "Loading conferences…",
  insc_retry: "Retry",
  insc_empty: "No conferences found with those filters.",
  insc_spots_none: "No spots available",
  insc_spots: "spot available",
  insc_spots_pl: "spots available",
  insc_register: "Register",
  insc_cancel: "Cancel registration",
  insc_registering: "Registering…",
  insc_cancelling: "Cancelling…",
  insc_full: "Full",
  insc_registered_badge: "Registered",
  insc_to_define: "To be defined",
  /* Official categories */
  cat_software: "Software Engineering and Information Systems",
  cat_ai:       "Artificial Intelligence and Co-existence",
  cat_cities:   "Smart Cities and Sustainable Development",
  cat_security: "Security, Privacy and Infrastructure",
  cat_tech:     "Technology, Society and Innovation",
  /* Ticket */
  prof_ticket_sede: "VENUE", prof_ticket_sala: "ROOM", prof_ticket_serial: "SERIAL",
  prof_ticket_venue: "Universidad Católica de Colombia",
};

const IT: T = {
  home: "Home", nosotros: "Chi Siamo", ferias: "Le Nostre Fiere",
  inscripciones: "Conferenze", noticias: "Notizie", ponentes: "Relatori", login: "Accedi",
  register: "Registrati",
  buscar: "Cerca...",
  hero_title: "Coniiti 2026", hero_country: "Paese ospite: Italia",
  hero_speakers: "Relatori internazionali",
  stat_speakers: "Relatori", stat_sponsors: "Sponsor",
  stat_workshops: "Workshop", stat_attendees: "Partecipanti",
  stat_host: "Paese ospitante", stat_days: "Giorni di evento",
  days: "Giorni", hours: "Ore", minutes: "Minuti", seconds: "Secondi",
  card1_title: "Home", card1_p: "Esplora le nostre informazioni principali.",
  card2_title: "Le Nostre Fiere", card2_p: "Eventi accademici e aziendali.",
  card3_title: "Iscrizioni", card3_p: "Scopri i passi per candidarsi.",
  card4_title: "Notizie", card4_p: "Rimani informato.",
  nos_what: "Cos'è CONIITI?",
  nos_what_p: "Il Congresso Internazionale di Innovazione e Tendenze nell'Ingegneria è l'evento accademico di punta dell'Università Cattolica della Colombia. Nella sua XII edizione, CONIITI 2026 ha l'Italia come paese ospite.",
  nos_history: "Storia",
  nos_history_p: "Dal 2014, CONIITI è cresciuto da un evento nazionale a un congresso con presenza in più di 20 paesi. Ogni edizione ha promosso la pubblicazione di ricerche indicizzate.",
  nos_uni: "Università Organizzatrice",
  nos_uni_p: "L'Università Cattolica della Colombia, con oltre 50 anni di storia e accreditamento di alta qualità, è la sede di CONIITI.",
  nos_visit: "Visita il sito ufficiale →",
  nos_goals: "Obiettivi",
  goal1_t: "Internazionalizzazione", goal1_p: "Scambio di conoscenze tra ingegneri del mondo.",
  goal2_t: "Innovazione", goal2_p: "Ultime tendenze tecnologiche e ricerche applicate.",
  goal3_t: "Networking", goal3_p: "Reti tra accademici, aziende e ricercatori.",
  goal4_t: "Formazione", goal4_p: "Rafforzamento delle competenze ingegneristiche.",
  fer_hero_tag: "XII Edizione · 2026",
  fer_hero_sub: "Congresso Internazionale di Innovazione e Tendenze nell'Ingegneria",
  fer_mission_label: "La Nostra Missione",
  fer_mission_q: "Uno spazio aperto di interazione tra attori dell'ecosistema dell'innovazione, volto a condividere nuovi approcci per la trasformazione creativa della Colombia attraverso soluzioni ingegneristiche.",
  fer_stat_editions: "Edizioni", fer_stat_countries: "Paesi",
  fer_stat_participants: "Partecipanti", fer_stat_spk: "Relatori",
  fer_editions_title: "Edizioni del Congresso",
  fer_editions_sub: "Esplora la storia di ogni edizione di CONIITI.",
  fer_card_2015: "Visualizza le informazioni sull'evento.",
  fer_coming_soon: "Prossimamente",
  fer_why: "Perché Partecipare?",
  fer_timeline: "Percorso del Congresso",
  fer_tl_2014: "Prima edizione nazionale presso l'Università Cattolica della Colombia.",
  fer_tl_2016: "Apertura internazionale con presentazioni di ingegneri dall'America Latina e dalla Spagna.",
  fer_tl_2019: "Consolidamento accademico con indicizzazione degli atti in database internazionali.",
  fer_tl_2020: "Adattamento al formato virtuale, connettendo partecipanti in oltre 15 paesi.",
  fer_tl_2025: "XI edizione: 452+ partecipanti, 35 relatori e 5 workshop specializzati.",
  fer_tl_2026: "XII edizione con l'Italia come paese ospite in formato ibrido da Bogotá.",
  fer_dates_title: "Date Chiave — 2026",
  fer_date1_val: "30 Giu 2026", fer_date1_label: "Invio articoli",
  fer_date2_val: "18 Ago 2026", fer_date2_label: "Notifica accettazione",
  fer_date3_val: "30 Set – 2 Ott", fer_date3_label: "Evento ibrido",
  fer_includes: "La tua iscrizione include",
  fer_inc1: "Registrazione come relatore",
  fer_inc2: "Certificato ufficiale di partecipazione",
  fer_inc3: "Pubblicazione negli atti scientifici",
  fer_modalities: "Come Partecipare?",
  fer_modal_local: "Presenziale",
  fer_modal_local_desc: "Università Cattolica della Colombia, Sede 4, Bogotá, Colombia",
  fer_modal_virtual: "Virtuale",
  fer_modal_virtual_desc: "Streaming dal vivo per partecipanti di tutto il mondo",
  fer_partners_title: "Partner Strategici",
  fer_contact_title: "Contattaci",
  fer_contact_email_l: "Email",
  fer_contact_phone_l: "Telefono",
  fer_contact_addr_l: "Sede",
  fer_cta_title: "CONIITI 2026 ti aspetta",
  fer_format: "Bogotá, Colombia · Formato Ibrido",
  fer_cta_btn: "Iscriviti a CONIITI 2026",
  footer_center: "Centro Congressi",
  footer_rights: "© 2026 CONIITI - Tutti i diritti riservati",
  back: "Torna alla home",
  hero_edition: "XII Edizione · Bogotá, Colombia",
  hero_tagline: "Il congresso internazionale che connette l'ingegneria del futuro.",
  hero_cta: "Iscriviti al congresso",
  hero_city: "Bogotá, Colombia",
  hero_date: "23 settembre 2026",
  hero_guest: "Paese ospite",
  countdown_label: "Il congresso inizia tra",
  home_discover: "Scopri CONIITI 2026",
  home_discover_sub: "Esplora ogni angolo del congresso internazionale di ingegneria",
  insc_title: "Conferenze CONIITI 2026",
  insc_sub: "Esplora il catalogo di conferenze e iscriviti a quelle che ti interessano",
  insc_search_ph: "Cerca per titolo, relatore o tema…",
  insc_loading: "Caricamento conferenze…",
  insc_retry: "Riprova",
  insc_empty: "Nessuna conferenza trovata con questi filtri.",
  insc_spots_none: "Nessun posto disponibile",
  insc_spots: "posto disponibile",
  insc_spots_pl: "posti disponibili",
  insc_register: "Iscrivimi",
  insc_cancel: "Annulla iscrizione",
  insc_registering: "Iscrizione in corso…",
  insc_cancelling: "Annullamento…",
  insc_full: "Completo",
  insc_registered_badge: "Iscritto",
  insc_to_define: "Da definire",
  /* Categorie ufficiali */
  cat_software: "Ingegneria del Software e Sistemi Informativi",
  cat_ai:       "Intelligenza Artificiale e Co-esistenza",
  cat_cities:   "Città Intelligenti e Sviluppo Sostenibile",
  cat_security: "Sicurezza, Privacy e Infrastruttura",
  cat_tech:     "Tecnologia, Società e Innovazione",
  /* Dashboard nav */
  dash_profile: "Profilo", dash_conferences: "Le mie conferenze", dash_completed: "Completate",
  dash_favorites: "Preferiti", dash_calendar: "Calendario",
  dash_messages: "Messaggi", dash_settings: "Impostazioni", dash_logout: "Esci",
  dash_mobile_talks: "I miei talk", dash_go_home: "Inizio", dash_loading: "Caricamento…",
  dash_welcome_back: "Bentornato,", dash_welcome_first: "Benvenuto al CONIITI 2026!",
  dash_notifications: "Notifiche",
  dash_account_settings: "Impostazioni account", dash_section_account: "Account",
  /* ProfileView */
  prof_reg_date: "Data di registrazione:", prof_country: "Paese, città:",
  prof_birthdate: "Data di nascita:", prof_email: "E-mail:", prof_phone: "Telefono:",
  prof_upcoming: "Prossimo evento", prof_event_subtitle: "20 ottobre · Bogotá, Colombia",
  prof_days: "giorni", prof_hours: "ore", prof_min: "min", prof_seg: "sec",
  prof_day0: "Lun 20 Ott", prof_day1: "Mar 21 Ott", prof_day2: "Mer 22 Ott", prof_day3: "Gio 23 Ott",
  prof_no_tickets: "Nessun biglietto",
  prof_no_tickets_sub: "Non sei ancora iscritto a nessuna conferenza del CONIITI 2026.",
  prof_explore: "Esplora le conferenze", prof_prev: "Precedente", prof_next_ticket: "Successivo",
  prof_edit: "Modifica profilo", prof_loading: "Caricamento…",
  /* InscritasView */
  iv_kpi_total: "Totale iscritte", iv_kpi_confirmed: "Confermate",
  iv_kpi_ongoing: "In corso", iv_kpi_finished: "Terminate",
  iv_search_ph: "Cerca per conferenza, relatore, sala o categoria...",
  iv_show_all: "Mostra Tutte", iv_conference_s: "conferenza", iv_conference_pl: "conferenze",
  iv_back_cats: "Torna alle Categorie", iv_no_results: "Nessuna conferenza trovata",
  iv_matching: "corrispondente a",
  iv_th_conference: "Conferenza", iv_th_category: "Categoria", iv_th_status: "Stato",
  iv_th_speaker: "Relatore", iv_th_location: "Ubicazione", iv_th_schedule: "Orario",
  iv_status_confirmed: "Confermata", iv_status_ongoing: "In corso", iv_status_finished: "Terminata",
  iv_cancel_action: "Annulla iscrizione", iv_loading: "Caricamento delle conferenze…",
  iv_empty_title: "Non hai ancora conferenze iscritte al CONIITI 2026",
  iv_empty_sub: "Esplora il programma e iscriviti alle tue preferite!",
  iv_explore: "Esplora le conferenze", iv_no_results_cat: "Nessuna conferenza in questa categoria",
  iv_no_results_q: "Nessun risultato per", iv_cancel_ok: "Iscrizione a \"{0}\" annullata",
  iv_cancel_fail: "Impossibile annullare l'iscrizione", iv_conn_error: "Errore di connessione",
  iv_load_error: "Impossibile caricare le conferenze",
  /* SettingsView */
  stv_tab_profile: "Dati del profilo", stv_tab_security: "Sicurezza", stv_tab_prefs: "Preferenze",
  stv_field_name: "Nome completo", stv_field_phone: "Telefono",
  stv_field_city: "Città / Paese", stv_field_birthdate: "Data di nascita",
  stv_save: "Salva modifiche", stv_saving: "Salvataggio…",
  stv_saved_ok: "Profilo aggiornato con successo.",
  stv_save_error: "Impossibile salvare. Verifica la connessione.",
  stv_field_cur_pwd: "Password attuale", stv_field_new_pwd: "Nuova password",
  stv_field_confirm_pwd: "Conferma nuova password",
  stv_pwd_min_hint: "Minimo 6 caratteri", stv_pwd_repeat_hint: "Ripeti la password",
  stv_update_pwd: "Aggiorna password", stv_updating: "Aggiornamento…",
  stv_pwd_ok: "Password aggiornata con successo.",
  stv_pwd_short: "La nuova password deve avere almeno 6 caratteri.",
  stv_pwd_mismatch: "Le nuove password non coincidono.",
  stv_pwd_error: "Impossibile aggiornare la password.",
  stv_theme_title: "Tema dell'interfaccia",
  stv_theme_light: "Chiaro UCC", stv_theme_light_desc: "Blu e bianco istituzionale",
  stv_theme_dark: "Scuro UCC", stv_theme_dark_desc: "Modalità notturna con accenti dorati",
  stv_theme_system: "Sistema", stv_theme_system_desc: "Segue le preferenze del dispositivo",
  stv_compact_title: "Vista compatta",
  stv_compact_on: "Abilitata — meno spazio tra gli elementi",
  stv_compact_off: "Disabilitata — spaziatura standard",
  stv_avatar_change: "Cambia foto profilo",
  stv_2fa_title: "Autenticazione a Due Fattori (2FA)",
  stv_2fa_desc: "Aumenta la sicurezza del tuo account richiedendo un codice di verifica ad ogni accesso.",
  stv_2fa_enabled: "2FA attivato",
  stv_2fa_disabled: "2FA disattivato",
  stv_sessions_title: "Sessioni attive",
  stv_session_badge: "Sessione attiva",
  stv_notif_title: "Notifiche",
  stv_notif_conf: "Conferme di iscrizione alle conferenze",
  stv_notif_cancel: "Avvisi di conferenze cancellate o modificate",
  stv_timefmt_title: "Formato dell'ora",
  stv_timefmt_12: "12 ore (AM/PM)",
  stv_timefmt_24: "24 ore (Militare)",
  /* MessagesView */
  msv_loading: "Caricamento messaggi…", msv_error: "Impossibile caricare i messaggi.",
  msv_empty_title: "Nessun messaggio",
  msv_empty_sub: "Quando il sistema ti invierà notifiche, appariranno qui.",
  msv_heading: "Messaggi", msv_unread: "{0} non letti", msv_mark_read: "Segna come letto",
  msv_unread_label: "Non letto", msv_type_info: "Info", msv_type_alerta: "Allerta",
  msv_type_sistema: "Sistema",
  msv_center_title: "Centro Notifiche",
  msv_tab_all: "Tutte", msv_tab_unread: "Non lette",
  msv_mark_all_read: "Segna tutte come lette",
  msv_empty_notif: "Nessuna notifica in sospeso qui.",
  msv_time_now: "Adesso", msv_time_min: "{0} min fa", msv_time_hour: "{0} h fa",
  msv_time_today: "Oggi, {0}", msv_time_yesterday: "Ieri, {0}",
  msv_back_inbox: "Torna alla posta", msv_label_inbox: "Posta in arrivo",
  msv_to_me: "a me",
  msv_ticket_label: "Biglietto d'ingresso", msv_ticket_access: "Accesso confermato",
  msv_reply_close: "Rispondi (Chiudi)", msv_mark_unread: "Segna come non letto",
  msv_adv_search: "Ricerca avanzata", msv_adv_date_range: "Intervallo di date",
  msv_adv_today: "Oggi", msv_adv_week: "Ultima settimana",
  msv_adv_from: "Da", msv_adv_to: "A",
  msv_adv_theme: "Linea tematica", msv_adv_theme_all: "Tutte le linee",
  msv_adv_keyword: "Parola chiave", msv_adv_keyword_ph: "Cerca nel corpo del messaggio...",
  msv_adv_clear: "Cancella filtri", msv_adv_apply: "Applica filtri",
  msv_adv_no_results: "Nessuna notifica trovata con questi filtri.",
  /* PlaceholderView */
  ph_favorites_title: "Preferiti", ph_favorites_msg: "Funzione preferiti disponibile a breve.",
  ph_completed_title: "Completate",
  ph_system_ready: "Il sistema è pronto per ricevere questi dati nella prossima fase del progetto.",
  ph_soon: "Prossimamente", ph_dev_title: "Sezione in sviluppo",
  ph_dev_msg: "Questa funzionalità sarà disponibile a breve.",
  /* CompletedConferencesView */
  ccv_heading: "Storico Presenze",
  ccv_search_ph: "Cerca per conferenza o relatore...",
  ccv_th_conference: "Nome della Conferenza", ccv_th_speaker: "Relatore",
  ccv_th_location: "Ubicazione", ccv_th_date: "Data", ccv_th_action: "Azione",
  ccv_cert_btn: "Scarica Certificato",
  ccv_loading: "Caricamento storico…", ccv_load_error: "Impossibile caricare lo storico",
  ccv_empty_title: "Nessuna presenza registrata per conferenze concluse.",
  ccv_empty_sub: "Ricorda di scansionare il QR code all'ingresso.",
  ccv_showing: "Visualizzazione record", ccv_no_results: "Nessun risultato per questa ricerca",
  ccv_filter_label: "Categoria", ccv_filter_all: "Tutte",
  ccv_sort_by: "Ordina", ccv_sort_newest: "Più recenti", ccv_sort_oldest: "Più antichi",
  /* Ticket */
  prof_ticket_sede: "SEDE", prof_ticket_sala: "SALA", prof_ticket_serial: "SERIALE",
  prof_ticket_venue: "Universidad Católica de Colombia",
};

const PT: T = {
  home: "Início", nosotros: "Sobre Nós", ferias: "Nossas Feiras",
  inscripciones: "Conferências", noticias: "Notícias", ponentes: "Palestrantes", login: "Entrar",
  register: "Cadastrar",
  buscar: "Buscar...",
  hero_title: "Coniiti 2026", hero_country: "País convidado: Itália",
  hero_speakers: "Palestrantes internacionais",
  stat_speakers: "Palestrantes", stat_sponsors: "Patrocinadores",
  stat_workshops: "Oficinas", stat_attendees: "Participantes",
  stat_host: "País anfitrião", stat_days: "Dias de evento",
  days: "Dias", hours: "Horas", minutes: "Minutos", seconds: "Segundos",
  card1_title: "Início", card1_p: "Explore nossas informações principais.",
  card2_title: "Nossas Feiras", card2_p: "Eventos acadêmicos e empresariais.",
  card3_title: "Inscrições", card3_p: "Conheça os passos para se inscrever.",
  card4_title: "Notícias", card4_p: "Fique informado.",
  nos_what: "O que é CONIITI?",
  nos_what_p: "O Congresso Internacional de Inovação e Tendências em Engenharia é o evento acadêmico principal da Universidade Católica da Colômbia. Em sua XII edição, CONIITI 2026 tem a Itália como país convidado.",
  nos_history: "História",
  nos_history_p: "Desde 2014, o CONIITI cresceu de um evento nacional para um congresso com presença em mais de 20 países.",
  nos_uni: "Universidade Organizadora",
  nos_uni_p: "A Universidade Católica da Colômbia, com mais de 50 anos de história e acreditação de alta qualidade, é a sede do CONIITI.",
  nos_visit: "Visitar site oficial →",
  nos_goals: "Objetivos",
  goal1_t: "Internacionalização", goal1_p: "Troca de conhecimento entre engenheiros do mundo.",
  goal2_t: "Inovação", goal2_p: "Últimas tendências tecnológicas e pesquisas aplicadas.",
  goal3_t: "Networking", goal3_p: "Redes entre acadêmicos, empresas e pesquisadores.",
  goal4_t: "Formação", goal4_p: "Fortalecimento de competências em engenharia.",
  fer_hero_tag: "XII Edição · 2026",
  fer_hero_sub: "Congresso Internacional de Inovação e Tendências em Engenharia",
  fer_mission_label: "Nossa Missão",
  fer_mission_q: "Um espaço aberto de interação entre atores do ecossistema de inovação, voltado para compartilhar novas abordagens para a transformação criativa da Colômbia por meio de soluções de engenharia.",
  fer_stat_editions: "Edições", fer_stat_countries: "Países",
  fer_stat_participants: "Participantes", fer_stat_spk: "Palestrantes",
  fer_editions_title: "Edições do Congresso",
  fer_editions_sub: "Explore a história de cada edição do CONIITI.",
  fer_card_2015: "Ver informações do evento.",
  fer_coming_soon: "Em Breve",
  fer_why: "Por que Participar?",
  fer_timeline: "Trajetória do Congresso",
  fer_tl_2014: "Primeira edição nacional na Universidade Católica da Colômbia, estabelecendo as bases do congresso.",
  fer_tl_2016: "Abertura internacional com apresentações de engenheiros da América Latina e Espanha.",
  fer_tl_2019: "Consolidação acadêmica com indexação de anais em bases de dados internacionais.",
  fer_tl_2020: "Adaptação ao formato virtual, conectando participantes em mais de 15 países.",
  fer_tl_2025: "XI edição: 452+ participantes, 35 palestrantes e 5 oficinas especializadas.",
  fer_tl_2026: "XII edição com Itália como país convidado em formato híbrido a partir de Bogotá.",
  fer_dates_title: "Datas Importantes — 2026",
  fer_date1_val: "30 Jun 2026", fer_date1_label: "Envio de artigos",
  fer_date2_val: "18 Ago 2026", fer_date2_label: "Notificação de aceitação",
  fer_date3_val: "30 Set – 2 Out", fer_date3_label: "Evento híbrido",
  fer_includes: "Sua inscrição inclui",
  fer_inc1: "Registro como palestrante",
  fer_inc2: "Certificado oficial de participação",
  fer_inc3: "Publicação em anais científicos",
  fer_modalities: "Como Participar?",
  fer_modal_local: "Presencial",
  fer_modal_local_desc: "Universidade Católica da Colômbia, Sede 4, Bogotá, Colômbia",
  fer_modal_virtual: "Virtual",
  fer_modal_virtual_desc: "Transmissão ao vivo para participantes do mundo todo",
  fer_partners_title: "Parceiros Estratégicos",
  fer_contact_title: "Contate-nos",
  fer_contact_email_l: "E-mail",
  fer_contact_phone_l: "Telefone",
  fer_contact_addr_l: "Sede",
  fer_cta_title: "CONIITI 2026 te aguarda",
  fer_format: "Bogotá, Colômbia · Formato Híbrido",
  fer_cta_btn: "Inscreva-se no CONIITI 2026",
  footer_center: "Centro de Convenções",
  footer_rights: "© 2026 CONIITI - Todos os direitos reservados",
  back: "Voltar ao início",
  hero_edition: "XII Edição · Bogotá, Colômbia",
  hero_tagline: "O congresso internacional que conecta a engenharia do futuro.",
  hero_cta: "Inscreva-se no congresso",
  hero_city: "Bogotá, Colômbia",
  hero_date: "23 de setembro de 2026",
  hero_guest: "País convidado",
  countdown_label: "O congresso começa em",
  home_discover: "Descubra o CONIITI 2026",
  home_discover_sub: "Explore cada canto do congresso internacional de engenharia",
  insc_title: "Conferências CONIITI 2026",
  insc_sub: "Explore o catálogo de palestras e inscreva-se nas que mais lhe interessam",
  insc_search_ph: "Buscar por título, palestrante ou tema…",
  insc_loading: "Carregando conferências…",
  insc_retry: "Tentar novamente",
  insc_empty: "Nenhuma conferência encontrada com esses filtros.",
  insc_spots_none: "Sem vagas disponíveis",
  insc_spots: "vaga disponível",
  insc_spots_pl: "vagas disponíveis",
  insc_register: "Inscrever-me",
  insc_cancel: "Cancelar inscrição",
  insc_registering: "Inscrevendo…",
  insc_cancelling: "Cancelando…",
  insc_full: "Sem vagas",
  insc_registered_badge: "Inscrito",
  insc_to_define: "A definir",
  /* Categorias oficiais */
  cat_software: "Engenharia de Software e Sistemas de Informação",
  cat_ai:       "Inteligência Artificial e Co-existência",
  cat_cities:   "Cidades Inteligentes e Desenvolvimento Sustentável",
  cat_security: "Segurança, Privacidade e Infraestrutura",
  cat_tech:     "Tecnologia, Sociedade e Inovação",
  /* Dashboard nav */
  dash_profile: "Perfil", dash_conferences: "Minhas conferências", dash_completed: "Concluídas",
  dash_favorites: "Favoritos", dash_calendar: "Calendário",
  dash_messages: "Mensagens", dash_settings: "Configurações", dash_logout: "Sair",
  dash_mobile_talks: "Minhas palestras", dash_go_home: "Início", dash_loading: "Carregando…",
  dash_welcome_back: "Bem-vindo de volta,", dash_welcome_first: "Bem-vindo ao CONIITI 2026!",
  dash_notifications: "Notificações",
  dash_account_settings: "Configurações da conta", dash_section_account: "Conta",
  /* ProfileView */
  prof_reg_date: "Data de registro:", prof_country: "País, cidade:",
  prof_birthdate: "Data de nascimento:", prof_email: "E-mail:", prof_phone: "Telefone:",
  prof_upcoming: "Próximo evento", prof_event_subtitle: "20 outubro · Bogotá, Colômbia",
  prof_days: "dias", prof_hours: "horas", prof_min: "min", prof_seg: "seg",
  prof_day0: "Seg 20 Out", prof_day1: "Ter 21 Out", prof_day2: "Qua 22 Out", prof_day3: "Qui 23 Out",
  prof_no_tickets: "Sem ingressos",
  prof_no_tickets_sub: "Você ainda não está inscrito em nenhuma conferência do CONIITI 2026.",
  prof_explore: "Explorar conferências", prof_prev: "Anterior", prof_next_ticket: "Próximo",
  prof_edit: "Editar perfil", prof_loading: "Carregando…",
  /* InscritasView */
  iv_kpi_total: "Total inscritas", iv_kpi_confirmed: "Confirmadas",
  iv_kpi_ongoing: "Em andamento", iv_kpi_finished: "Finalizadas",
  iv_search_ph: "Buscar por conferência, palestrante, sala ou categoria...",
  iv_show_all: "Mostrar Todas", iv_conference_s: "conferência", iv_conference_pl: "conferências",
  iv_back_cats: "Voltar às Categorias", iv_no_results: "Nenhuma conferência encontrada",
  iv_matching: "correspondente a",
  iv_th_conference: "Conferência", iv_th_category: "Categoria", iv_th_status: "Status",
  iv_th_speaker: "Palestrante", iv_th_location: "Localização", iv_th_schedule: "Horário",
  iv_status_confirmed: "Confirmada", iv_status_ongoing: "Em andamento", iv_status_finished: "Finalizada",
  iv_cancel_action: "Cancelar inscrição", iv_loading: "Carregando suas conferências…",
  iv_empty_title: "Você ainda não tem conferências inscritas no CONIITI 2026",
  iv_empty_sub: "Explore a programação e inscreva-se nas suas favoritas!",
  iv_explore: "Explorar conferências", iv_no_results_cat: "Nenhuma conferência nesta categoria",
  iv_no_results_q: "Sem resultados para", iv_cancel_ok: "Inscrição em \"{0}\" cancelada",
  iv_cancel_fail: "Não foi possível cancelar a inscrição", iv_conn_error: "Erro de conexão",
  iv_load_error: "Não foi possível carregar as conferências",
  /* SettingsView */
  stv_tab_profile: "Dados do perfil", stv_tab_security: "Segurança", stv_tab_prefs: "Preferências",
  stv_field_name: "Nome completo", stv_field_phone: "Telefone",
  stv_field_city: "Cidade / País", stv_field_birthdate: "Data de nascimento",
  stv_save: "Salvar alterações", stv_saving: "Salvando…",
  stv_saved_ok: "Perfil atualizado com sucesso.",
  stv_save_error: "Não foi possível salvar. Verifique sua conexão.",
  stv_field_cur_pwd: "Senha atual", stv_field_new_pwd: "Nova senha",
  stv_field_confirm_pwd: "Confirmar nova senha",
  stv_pwd_min_hint: "Mínimo 6 caracteres", stv_pwd_repeat_hint: "Repita a senha",
  stv_update_pwd: "Atualizar senha", stv_updating: "Atualizando…",
  stv_pwd_ok: "Senha atualizada com sucesso.",
  stv_pwd_short: "A nova senha deve ter pelo menos 6 caracteres.",
  stv_pwd_mismatch: "As novas senhas não coincidem.",
  stv_pwd_error: "Não foi possível atualizar a senha.",
  stv_theme_title: "Tema da interface",
  stv_theme_light: "Claro UCC", stv_theme_light_desc: "Azul e branco institucional",
  stv_theme_dark: "Escuro UCC", stv_theme_dark_desc: "Modo noturno com acentos dourados",
  stv_theme_system: "Sistema", stv_theme_system_desc: "Segue a preferência do dispositivo",
  stv_compact_title: "Vista compacta",
  stv_compact_on: "Ativada — menos espaço entre elementos",
  stv_compact_off: "Desativada — espaçamento padrão",
  stv_avatar_change: "Alterar foto de perfil",
  stv_2fa_title: "Autenticação de Dois Fatores (2FA)",
  stv_2fa_desc: "Aumente a segurança da sua conta solicitando um código de verificação em cada login.",
  stv_2fa_enabled: "2FA ativado",
  stv_2fa_disabled: "2FA desativado",
  stv_sessions_title: "Sessões ativas",
  stv_session_badge: "Sessão ativa",
  stv_notif_title: "Notificações",
  stv_notif_conf: "Confirmações de inscrição em conferências",
  stv_notif_cancel: "Alertas de conferências canceladas ou modificadas",
  stv_timefmt_title: "Formato de hora",
  stv_timefmt_12: "12 horas (AM/PM)",
  stv_timefmt_24: "24 horas (Militar)",
  /* MessagesView */
  msv_loading: "Carregando mensagens…", msv_error: "Não foi possível carregar as mensagens.",
  msv_empty_title: "Sem mensagens",
  msv_empty_sub: "Quando o sistema enviar notificações, elas aparecerão aqui.",
  msv_heading: "Mensagens", msv_unread: "{0} não lidas", msv_mark_read: "Marcar como lida",
  msv_unread_label: "Não lida", msv_type_info: "Info", msv_type_alerta: "Alerta",
  msv_type_sistema: "Sistema",
  msv_center_title: "Central de Notificações",
  msv_tab_all: "Todas", msv_tab_unread: "Não lidas",
  msv_mark_all_read: "Marcar todas como lidas",
  msv_empty_notif: "Sem notificações pendentes aqui.",
  msv_time_now: "Agora", msv_time_min: "Há {0} min", msv_time_hour: "Há {0} h",
  msv_time_today: "Hoje, {0}", msv_time_yesterday: "Ontem, {0}",
  msv_back_inbox: "Voltar à caixa", msv_label_inbox: "Caixa de entrada",
  msv_to_me: "para mim",
  msv_ticket_label: "Passe de entrada", msv_ticket_access: "Acesso confirmado",
  msv_reply_close: "Responder (Fechar)", msv_mark_unread: "Marcar como não lida",
  msv_adv_search: "Busca avançada", msv_adv_date_range: "Intervalo de datas",
  msv_adv_today: "Hoje", msv_adv_week: "Última semana",
  msv_adv_from: "De", msv_adv_to: "Até",
  msv_adv_theme: "Linha temática", msv_adv_theme_all: "Todas as linhas",
  msv_adv_keyword: "Palavra-chave", msv_adv_keyword_ph: "Buscar no corpo da mensagem...",
  msv_adv_clear: "Limpar filtros", msv_adv_apply: "Aplicar filtros",
  msv_adv_no_results: "Nenhuma notificação encontrada com esses filtros.",
  /* PlaceholderView */
  ph_favorites_title: "Favoritos", ph_favorites_msg: "Função de favoritos em breve.",
  ph_completed_title: "Concluídas",
  ph_system_ready: "O sistema está pronto para receber estes dados na próxima fase do projeto.",
  ph_soon: "Em breve", ph_dev_title: "Seção em desenvolvimento",
  ph_dev_msg: "Esta funcionalidade estará disponível em breve.",
  /* CompletedConferencesView */
  ccv_heading: "Histórico de Presença",
  ccv_search_ph: "Buscar por conferência ou palestrante...",
  ccv_th_conference: "Nome da Conferência", ccv_th_speaker: "Palestrante",
  ccv_th_location: "Localização", ccv_th_date: "Data", ccv_th_action: "Ação",
  ccv_cert_btn: "Baixar Certificado",
  ccv_loading: "Carregando histórico…", ccv_load_error: "Não foi possível carregar o histórico",
  ccv_empty_title: "Você ainda não tem presenças registradas em conferências concluídas.",
  ccv_empty_sub: "Lembre-se de escanear seu QR code ao entrar na sala.",
  ccv_showing: "Mostrando registros", ccv_no_results: "Sem resultados para esta pesquisa",
  ccv_filter_label: "Categoria", ccv_filter_all: "Todas",
  ccv_sort_by: "Ordenar", ccv_sort_newest: "Mais recentes", ccv_sort_oldest: "Mais antigas",
  /* Ticket */
  prof_ticket_sede: "LOCAL", prof_ticket_sala: "SALA", prof_ticket_serial: "SERIAL",
  prof_ticket_venue: "Universidad Católica de Colombia",
};

const FR: T = {
  home: "Accueil", nosotros: "À propos", ferias: "Nos Foires",
  inscripciones: "Conférences", noticias: "Actualités", ponentes: "Intervenants", login: "Connexion",
  register: "S'inscrire",
  buscar: "Rechercher...",
  hero_title: "Coniiti 2026", hero_country: "Pays invité : Italie",
  hero_speakers: "Conférenciers internationaux",
  stat_speakers: "Conférenciers", stat_sponsors: "Sponsors",
  stat_workshops: "Ateliers", stat_attendees: "Participants",
  stat_host: "Pays hôte", stat_days: "Jours d'événement",
  days: "Jours", hours: "Heures", minutes: "Minutes", seconds: "Secondes",
  card1_title: "Accueil", card1_p: "Explorez nos informations principales.",
  card2_title: "Nos Foires", card2_p: "Événements académiques et d'entreprise.",
  card3_title: "Inscriptions", card3_p: "Découvrez les étapes pour postuler.",
  card4_title: "Actualités", card4_p: "Restez informé.",
  nos_what: "Qu'est-ce que CONIITI ?",
  nos_what_p: "Le Congrès International d'Innovation et de Tendances en Ingénierie est l'événement académique phare de l'Université Catholique de Colombie. Dans sa XIIe édition, CONIITI 2026 accueille l'Italie comme pays invité.",
  nos_history: "Histoire",
  nos_history_p: "Depuis 2014, CONIITI est passé d'un événement national à un congrès présent dans plus de 20 pays.",
  nos_uni: "Université Organisatrice",
  nos_uni_p: "L'Université Catholique de Colombie, avec plus de 50 ans d'histoire et une accréditation de haute qualité, est le siège de CONIITI.",
  nos_visit: "Visiter le site officiel →",
  nos_goals: "Objectifs",
  goal1_t: "Internationalisation", goal1_p: "Échange de connaissances entre ingénieurs du monde entier.",
  goal2_t: "Innovation", goal2_p: "Dernières tendances technologiques et recherches appliquées.",
  goal3_t: "Networking", goal3_p: "Réseaux entre universitaires, entreprises et chercheurs.",
  goal4_t: "Formation", goal4_p: "Renforcement des compétences en ingénierie.",
  fer_hero_tag: "XIIe Édition · 2026",
  fer_hero_sub: "Congrès International d'Innovation et de Tendances en Ingénierie",
  fer_mission_label: "Notre Mission",
  fer_mission_q: "Un espace ouvert d'interaction entre acteurs de l'écosystème d'innovation, visant à partager de nouvelles approches pour la transformation créative de la Colombie à travers des solutions d'ingénierie.",
  fer_stat_editions: "Éditions", fer_stat_countries: "Pays",
  fer_stat_participants: "Participants", fer_stat_spk: "Conférenciers",
  fer_editions_title: "Éditions du Congrès",
  fer_editions_sub: "Explorez l'histoire de chaque édition de CONIITI.",
  fer_card_2015: "Voir les informations sur l'événement.",
  fer_coming_soon: "Prochainement",
  fer_why: "Pourquoi Participer ?",
  fer_timeline: "Parcours du Congrès",
  fer_tl_2014: "Première édition nationale à l'Université Catholique de Colombie, posant les bases du congrès.",
  fer_tl_2016: "Ouverture internationale avec des présentations d'ingénieurs d'Amérique latine et d'Espagne.",
  fer_tl_2019: "Consolidation académique avec indexation des actes dans des bases de données internationales.",
  fer_tl_2020: "Adaptation au format virtuel, reliant des participants dans plus de 15 pays.",
  fer_tl_2025: "XIe édition : 452+ participants, 35 conférenciers et 5 ateliers spécialisés.",
  fer_tl_2026: "XIIe édition avec l'Italie comme pays invité en format hybride depuis Bogotá.",
  fer_dates_title: "Dates Clés — 2026",
  fer_date1_val: "30 Juin 2026", fer_date1_label: "Soumission d'articles",
  fer_date2_val: "18 Aoû 2026", fer_date2_label: "Notification d'acceptation",
  fer_date3_val: "30 Sep – 2 Oct", fer_date3_label: "Événement hybride",
  fer_includes: "Votre inscription comprend",
  fer_inc1: "Inscription comme conférencier",
  fer_inc2: "Certificat officiel de participation",
  fer_inc3: "Publication dans les actes scientifiques",
  fer_modalities: "Comment Participer ?",
  fer_modal_local: "Présentiel",
  fer_modal_local_desc: "Université Catholique de Colombie, Siège 4, Bogotá, Colombie",
  fer_modal_virtual: "Virtuel",
  fer_modal_virtual_desc: "Diffusion en direct pour les participants du monde entier",
  fer_partners_title: "Partenaires Stratégiques",
  fer_contact_title: "Contactez-nous",
  fer_contact_email_l: "Email",
  fer_contact_phone_l: "Téléphone",
  fer_contact_addr_l: "Siège",
  fer_cta_title: "CONIITI 2026 vous attend",
  fer_format: "Bogotá, Colombie · Format Hybride",
  fer_cta_btn: "S'inscrire à CONIITI 2026",
  footer_center: "Centre de Conventions",
  footer_rights: "© 2026 CONIITI - Tous droits réservés",
  back: "Retour à l'accueil",
  hero_edition: "XIIe Édition · Bogotá, Colombie",
  hero_tagline: "Le congrès international qui connecte l'ingénierie du futur.",
  hero_cta: "S'inscrire au congrès",
  hero_city: "Bogotá, Colombie",
  hero_date: "23 septembre 2026",
  hero_guest: "Pays invité",
  countdown_label: "Le congrès commence dans",
  home_discover: "Découvrez CONIITI 2026",
  home_discover_sub: "Explorez chaque recoin du congrès international d'ingénierie",
  insc_title: "Conférences CONIITI 2026",
  insc_sub: "Parcourez le catalogue et inscrivez-vous aux conférences qui vous intéressent",
  insc_search_ph: "Rechercher par titre, intervenant ou thème…",
  insc_loading: "Chargement des conférences…",
  insc_retry: "Réessayer",
  insc_empty: "Aucune conférence trouvée avec ces filtres.",
  insc_spots_none: "Plus de places disponibles",
  insc_spots: "place disponible",
  insc_spots_pl: "places disponibles",
  insc_register: "M'inscrire",
  insc_cancel: "Annuler l'inscription",
  insc_registering: "Inscription en cours…",
  insc_cancelling: "Annulation…",
  insc_full: "Complet",
  insc_registered_badge: "Inscrit",
  insc_to_define: "À définir",
  /* Catégories officielles */
  cat_software: "Génie Logiciel et Systèmes d'Information",
  cat_ai:       "Intelligence Artificielle et Co-existence",
  cat_cities:   "Villes Intelligentes et Développement Durable",
  cat_security: "Sécurité, Confidentialité et Infrastructure",
  cat_tech:     "Technologie, Société et Innovation",
  /* Dashboard nav */
  dash_profile: "Profil", dash_conferences: "Mes conférences", dash_completed: "Terminées",
  dash_favorites: "Favoris", dash_calendar: "Calendrier",
  dash_messages: "Messages", dash_settings: "Paramètres", dash_logout: "Se déconnecter",
  dash_mobile_talks: "Mes conférences", dash_go_home: "Accueil", dash_loading: "Chargement…",
  dash_welcome_back: "Bon retour,", dash_welcome_first: "Bienvenue au CONIITI 2026 !",
  dash_notifications: "Notifications",
  dash_account_settings: "Paramètres du compte", dash_section_account: "Compte",
  /* ProfileView */
  prof_reg_date: "Date d'inscription :", prof_country: "Pays, ville :",
  prof_birthdate: "Date de naissance :", prof_email: "E-mail :", prof_phone: "Téléphone :",
  prof_upcoming: "Prochain événement", prof_event_subtitle: "20 octobre · Bogotá, Colombie",
  prof_days: "jours", prof_hours: "heures", prof_min: "min", prof_seg: "sec",
  prof_day0: "Lun 20 Oct", prof_day1: "Mar 21 Oct", prof_day2: "Mer 22 Oct", prof_day3: "Jeu 23 Oct",
  prof_no_tickets: "Pas de billets",
  prof_no_tickets_sub: "Vous n'êtes pas encore inscrit à une conférence du CONIITI 2026.",
  prof_explore: "Explorer les conférences", prof_prev: "Précédent", prof_next_ticket: "Suivant",
  prof_edit: "Modifier le profil", prof_loading: "Chargement…",
  /* InscritasView */
  iv_kpi_total: "Total inscrites", iv_kpi_confirmed: "Confirmées",
  iv_kpi_ongoing: "En cours", iv_kpi_finished: "Terminées",
  iv_search_ph: "Rechercher par conférence, intervenant, salle ou catégorie...",
  iv_show_all: "Afficher Toutes", iv_conference_s: "conférence", iv_conference_pl: "conférences",
  iv_back_cats: "Retour aux Catégories", iv_no_results: "Aucune conférence trouvée",
  iv_matching: "correspondant à",
  iv_th_conference: "Conférence", iv_th_category: "Catégorie", iv_th_status: "Statut",
  iv_th_speaker: "Intervenant", iv_th_location: "Lieu", iv_th_schedule: "Horaire",
  iv_status_confirmed: "Confirmée", iv_status_ongoing: "En cours", iv_status_finished: "Terminée",
  iv_cancel_action: "Annuler l'inscription", iv_loading: "Chargement de vos conférences…",
  iv_empty_title: "Vous n'avez pas encore de conférences au CONIITI 2026",
  iv_empty_sub: "Explorez le programme et inscrivez-vous à vos préférées !",
  iv_explore: "Explorer les conférences", iv_no_results_cat: "Aucune conférence dans cette catégorie",
  iv_no_results_q: "Aucun résultat pour", iv_cancel_ok: "Inscription à \"{0}\" annulée",
  iv_cancel_fail: "Impossible d'annuler l'inscription", iv_conn_error: "Erreur de connexion",
  iv_load_error: "Impossible de charger les conférences",
  /* SettingsView */
  stv_tab_profile: "Données du profil", stv_tab_security: "Sécurité", stv_tab_prefs: "Préférences",
  stv_field_name: "Nom complet", stv_field_phone: "Téléphone",
  stv_field_city: "Ville / Pays", stv_field_birthdate: "Date de naissance",
  stv_save: "Enregistrer les modifications", stv_saving: "Enregistrement…",
  stv_saved_ok: "Profil mis à jour avec succès.",
  stv_save_error: "Impossible d'enregistrer. Vérifiez votre connexion.",
  stv_field_cur_pwd: "Mot de passe actuel", stv_field_new_pwd: "Nouveau mot de passe",
  stv_field_confirm_pwd: "Confirmer le nouveau mot de passe",
  stv_pwd_min_hint: "Minimum 6 caractères", stv_pwd_repeat_hint: "Répétez le mot de passe",
  stv_update_pwd: "Mettre à jour le mot de passe", stv_updating: "Mise à jour…",
  stv_pwd_ok: "Mot de passe mis à jour avec succès.",
  stv_pwd_short: "Le nouveau mot de passe doit comporter au moins 6 caractères.",
  stv_pwd_mismatch: "Les nouveaux mots de passe ne correspondent pas.",
  stv_pwd_error: "Impossible de mettre à jour le mot de passe.",
  stv_theme_title: "Thème de l'interface",
  stv_theme_light: "Clair UCC", stv_theme_light_desc: "Bleu et blanc institutionnel",
  stv_theme_dark: "Sombre UCC", stv_theme_dark_desc: "Mode nuit avec accents dorés",
  stv_theme_system: "Système", stv_theme_system_desc: "Suit les préférences de l'appareil",
  stv_compact_title: "Vue compacte",
  stv_compact_on: "Activée — moins d'espace entre les éléments",
  stv_compact_off: "Désactivée — espacement standard",
  stv_avatar_change: "Changer la photo de profil",
  stv_2fa_title: "Authentification à Deux Facteurs (2FA)",
  stv_2fa_desc: "Renforcez la sécurité de votre compte en demandant un code de vérification à chaque connexion.",
  stv_2fa_enabled: "2FA activé",
  stv_2fa_disabled: "2FA désactivé",
  stv_sessions_title: "Sessions actives",
  stv_session_badge: "Session active",
  stv_notif_title: "Notifications",
  stv_notif_conf: "Confirmations d'inscription aux conférences",
  stv_notif_cancel: "Alertes de conférences annulées ou modifiées",
  stv_timefmt_title: "Format de l'heure",
  stv_timefmt_12: "12 heures (AM/PM)",
  stv_timefmt_24: "24 heures (Militaire)",
  /* MessagesView */
  msv_loading: "Chargement des messages…", msv_error: "Impossible de charger les messages.",
  msv_empty_title: "Pas de messages",
  msv_empty_sub: "Lorsque le système vous enverra des notifications, elles apparaîtront ici.",
  msv_heading: "Messages", msv_unread: "{0} non lus", msv_mark_read: "Marquer comme lu",
  msv_unread_label: "Non lu", msv_type_info: "Info", msv_type_alerta: "Alerte",
  msv_type_sistema: "Système",
  msv_center_title: "Centre de Notifications",
  msv_tab_all: "Toutes", msv_tab_unread: "Non lues",
  msv_mark_all_read: "Tout marquer comme lu",
  msv_empty_notif: "Aucune notification en attente ici.",
  msv_time_now: "À l'instant", msv_time_min: "Il y a {0} min", msv_time_hour: "Il y a {0} h",
  msv_time_today: "Aujourd'hui, {0}", msv_time_yesterday: "Hier, {0}",
  msv_back_inbox: "Retour à la boîte", msv_label_inbox: "Boîte de réception",
  msv_to_me: "à moi",
  msv_ticket_label: "Laissez-passer", msv_ticket_access: "Accès confirmé",
  msv_reply_close: "Répondre (Fermer)", msv_mark_unread: "Marquer comme non lu",
  msv_adv_search: "Recherche avancée", msv_adv_date_range: "Plage de dates",
  msv_adv_today: "Aujourd'hui", msv_adv_week: "Dernière semaine",
  msv_adv_from: "Du", msv_adv_to: "Au",
  msv_adv_theme: "Ligne thématique", msv_adv_theme_all: "Toutes les lignes",
  msv_adv_keyword: "Mot-clé", msv_adv_keyword_ph: "Rechercher dans le corps du message...",
  msv_adv_clear: "Effacer les filtres", msv_adv_apply: "Appliquer les filtres",
  msv_adv_no_results: "Aucune notification trouvée avec ces filtres.",
  /* PlaceholderView */
  ph_favorites_title: "Favoris", ph_favorites_msg: "Fonctionnalité favoris bientôt disponible.",
  ph_completed_title: "Terminées",
  ph_system_ready: "Le système est prêt à recevoir ces données lors de la prochaine phase du projet.",
  ph_soon: "Bientôt", ph_dev_title: "Section en développement",
  ph_dev_msg: "Cette fonctionnalité sera disponible prochainement.",
  /* CompletedConferencesView */
  ccv_heading: "Historique de Présence",
  ccv_search_ph: "Rechercher par conférence ou intervenant...",
  ccv_th_conference: "Nom de la Conférence", ccv_th_speaker: "Intervenant",
  ccv_th_location: "Lieu", ccv_th_date: "Date", ccv_th_action: "Action",
  ccv_cert_btn: "Télécharger le Certificat",
  ccv_loading: "Chargement de l'historique…", ccv_load_error: "Impossible de charger l'historique",
  ccv_empty_title: "Aucune présence enregistrée pour des conférences terminées.",
  ccv_empty_sub: "Pensez à scanner votre QR code en entrant dans la salle.",
  ccv_showing: "Affichage des enregistrements", ccv_no_results: "Aucun résultat pour cette recherche",
  ccv_filter_label: "Catégorie", ccv_filter_all: "Toutes",
  ccv_sort_by: "Trier", ccv_sort_newest: "Plus récentes", ccv_sort_oldest: "Plus anciennes",
  /* Ticket */
  prof_ticket_sede: "LIEU", prof_ticket_sala: "SALLE", prof_ticket_serial: "SÉRIE",
  prof_ticket_venue: "Universidad Católica de Colombia",
};

export const TRANSLATIONS: Record<LangCode, T> = { ES, EN, IT, PT, FR };

interface LanguageContextType {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: T;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ES", setLang: () => {}, t: ES,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(
    () => (localStorage.getItem("lang") as LangCode) || "ES"
  );
  const setLang = (l: LangCode) => { setLangState(l); localStorage.setItem("lang", l); };
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: TRANSLATIONS[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
